{
  "formatVersion": "1.1",
  "component": {
    "group": "com.highcapable.betterandroid",
    "module": "system-extension",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "system-extension-1.0.3.aar",
          "url": "system-extension-1.0.3.aar",
          "size": 53326,
          "sha512": "12279315ac887f0b30dfabc573a9e46cb514f2c99589d74a65d34786509b911d8461b1e9fdc0743fb1682713764ab125b4878fa508930b68cdae7d020814a272",
          "sha256": "72310a0a6e40699887c273149be1a19a3745ceaac51e5d5c7295fdd850f71518",
          "sha1": "f05826bff3247d7e8ed7d2e368f536be8ad54252",
          "md5": "7e85f0401930384a0b300af467a4c88e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.highcapable.kavaref",
          "module": "kavaref-core",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.highcapable.kavaref",
          "module": "kavaref-extension",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "system-extension-1.0.3.aar",
          "url": "system-extension-1.0.3.aar",
          "size": 53326,
          "sha512": "12279315ac887f0b30dfabc573a9e46cb514f2c99589d74a65d34786509b911d8461b1e9fdc0743fb1682713764ab125b4878fa508930b68cdae7d020814a272",
          "sha256": "72310a0a6e40699887c273149be1a19a3745ceaac51e5d5c7295fdd850f71518",
          "sha1": "f05826bff3247d7e8ed7d2e368f536be8ad54252",
          "md5": "7e85f0401930384a0b300af467a4c88e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "system-extension-1.0.3-sources.jar",
          "url": "system-extension-1.0.3-sources.jar",
          "size": 21816,
          "sha512": "2e79208667015b809d2cbf21fecbf7f0b80a8e2e613391f70ec566b823219c6c3ea7761ea2cbe2d687b03f2a99c482cd07517003ebea8779fe5ce3d985497e1d",
          "sha256": "df27242d315b4076c0c3733e9fa8579f83c78c69ce895da711f26c1b80a7d170",
          "sha1": "a5016935262b888cf9175dc3605410dd42a67b01",
          "md5": "81c3ab70a65caff0d5bd74a9ddbe71d9"
        }
      ]
    }
  ]
}
