{
  "formatVersion": "1.1",
  "component": {
    "group": "com.highcapable.hikage",
    "module": "hikage-extension-betterandroid",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "hikage-extension-betterandroid-1.0.2.aar",
          "url": "hikage-extension-betterandroid-1.0.2.aar",
          "size": 10902,
          "sha512": "169a6018b9958555b1e99bc8fbff99a867635f6e10c1c8ff7e9a6b0d7a0656108180c35fdfc3f733ac146e38d969ab0e50da74d121062e7262281ca6ca282ea4",
          "sha256": "060bad94da8b300b090bb45649d93700348cfed8f5035e8dc32c9a4f8ba3a507",
          "sha1": "29a1e20caa35fa6a2aa76111a0dfdb9b72dd4069",
          "md5": "c79340f6870eef2ebd1f40d041787502"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.highcapable.hikage",
          "module": "hikage-core",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.highcapable.kavaref",
          "module": "kavaref-core",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "com.highcapable.kavaref",
          "module": "kavaref-extension",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "com.highcapable.betterandroid",
          "module": "ui-component",
          "version": {
            "requires": "1.0.9"
          }
        },
        {
          "group": "com.highcapable.betterandroid",
          "module": "ui-component-adapter",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.highcapable.betterandroid",
          "module": "ui-extension",
          "version": {
            "requires": "1.0.8"
          }
        },
        {
          "group": "com.highcapable.betterandroid",
          "module": "system-extension",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "hikage-extension-betterandroid-1.0.2.aar",
          "url": "hikage-extension-betterandroid-1.0.2.aar",
          "size": 10902,
          "sha512": "169a6018b9958555b1e99bc8fbff99a867635f6e10c1c8ff7e9a6b0d7a0656108180c35fdfc3f733ac146e38d969ab0e50da74d121062e7262281ca6ca282ea4",
          "sha256": "060bad94da8b300b090bb45649d93700348cfed8f5035e8dc32c9a4f8ba3a507",
          "sha1": "29a1e20caa35fa6a2aa76111a0dfdb9b72dd4069",
          "md5": "c79340f6870eef2ebd1f40d041787502"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "hikage-extension-betterandroid-1.0.2-sources.jar",
          "url": "hikage-extension-betterandroid-1.0.2-sources.jar",
          "size": 8862,
          "sha512": "caab44dc26a5619b4227d95d78c652a9e9c0a08c7b63a6297747a30d1d73639c1f38ef98c1eebb245eb5d7ff0cd4e9761c6d68e660207a9f32e50ab1e74fe789",
          "sha256": "639264e2e23807823679cb91cc3a88d4a9459627f88bc70934dc2051d39d7d5d",
          "sha1": "236d12426cf331e8f209a78edee2ace2f3c16296",
          "md5": "6d378f88a2dab2c9132d8eff6574b102"
        }
      ]
    }
  ]
}
