{
  "formatVersion": "1.1",
  "component": {
    "group": "com.highcapable.betterandroid",
    "module": "ui-component",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.1.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "ui-component-1.0.1.aar",
          "url": "ui-component-1.0.1.aar",
          "size": 190437,
          "sha512": "ef4df3053226b8691977e541168e17ed1aef1a8767eddc190c0f60b0a36f7a554052f6ef4dbea339d177f123dd838ac3785dabe48a2ecf5fdee43203dbac1ddd",
          "sha256": "5b283bdd166f98f82f927fbbb2930f15eed0f229e7e2627f3e755821eaa5b55d",
          "sha1": "2f2949cff9c330fc8bd99d7f28bdc0f7baea08a3",
          "md5": "67cc51a669825b7d48500791da4b7ef3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.highcapable.betterandroid",
          "module": "ui-extension",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.highcapable.betterandroid",
          "module": "system-extension",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.highcapable.yukireflection",
          "module": "api",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.1.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "ui-component-1.0.1.aar",
          "url": "ui-component-1.0.1.aar",
          "size": 190437,
          "sha512": "ef4df3053226b8691977e541168e17ed1aef1a8767eddc190c0f60b0a36f7a554052f6ef4dbea339d177f123dd838ac3785dabe48a2ecf5fdee43203dbac1ddd",
          "sha256": "5b283bdd166f98f82f927fbbb2930f15eed0f229e7e2627f3e755821eaa5b55d",
          "sha1": "2f2949cff9c330fc8bd99d7f28bdc0f7baea08a3",
          "md5": "67cc51a669825b7d48500791da4b7ef3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-component-1.0.1-sources.jar",
          "url": "ui-component-1.0.1-sources.jar",
          "size": 74437,
          "sha512": "0cb179bd68b6c4caf4d814b9ace5ce519826dd1dc4f33517ce5d8b4df02662a5e6b6483b43b394ad7258447f85eb03f22f6c851896ae667f93fa7af733df9d72",
          "sha256": "9bcf67a1f1a91625608bb44fc5890a1186174c1012b144d6de0a2cda6d8ef6e9",
          "sha1": "949fe51db8a45bf3f7c08ce4fef1039af1542478",
          "md5": "673722ce509acb3e4496ab420504b539"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-component-1.0.1-javadoc.jar",
          "url": "ui-component-1.0.1-javadoc.jar",
          "size": 668749,
          "sha512": "4da41d8cef6310368a06365a702548c028e02b43a8c09ca64ad16b35ca2166ac0232b31b050f8ab2d9e6deb1ca918dd9493bf3422e204d757599e9d4601336fa",
          "sha256": "e4d3fa6cf818fad0da2041c63a89515bab218d69af786a7c9d45d24f5313f5ad",
          "sha1": "cb3cd3527420b919a890c11d0fd8550b9da23323",
          "md5": "a2a6c0e6d4b8aeef8877dab7c7ea8611"
        }
      ]
    }
  ]
}
