{
  "formatVersion": "1.1",
  "component": {
    "group": "com.highcapable.betterandroid",
    "module": "compose-multiplatform",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.5.11"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.5.11"
          }
        },
        {
          "group": "com.highcapable.betterandroid",
          "module": "compose-extension",
          "version": {
            "requires": "1.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "compose-multiplatform-metadata-0.1.0.jar",
          "url": "compose-multiplatform-0.1.0.jar",
          "size": 8946,
          "sha512": "2bcc0d51b4056ba24f45627219922f777d0af1e4793aaf6f95a7ed5a3c1cc9df2e84089d08b1aaafaf53109e7ff973427d839a51824fcd6f3331b4f478f3713f",
          "sha256": "aa1c2753f83a5e5fa3322c3bc3b19894e808b92511c5ab858153993e7cbc7244",
          "sha1": "3d62e118ebbd061e5e79e8ee42e128c63ba0d751",
          "md5": "1208bc14fad0a9684a4a2db495c6e9ec"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "compose-multiplatform-kotlin-0.1.0-sources.jar",
          "url": "compose-multiplatform-0.1.0-sources.jar",
          "size": 28201,
          "sha512": "dbf1d53318d784cf46faab9a874042c70bb324307d1323ec4bf7713c500298e261a36ee242ddf49083b85dcf5cc583a2cff7b45847aec77fbb71d9957208deaa",
          "sha256": "71305f026f7c91a3a9a149a31ac1173392c75350a5aeb3c8327208f66e46bb37",
          "sha1": "6778022ac1332c1125a2306709a5fd5c0dfa802a",
          "md5": "97991ebb03031643b55d1f9cdf7c44b8"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../compose-multiplatform-android/0.1.0/compose-multiplatform-android-0.1.0.module",
        "group": "com.highcapable.betterandroid",
        "module": "compose-multiplatform-android",
        "version": "0.1.0"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../compose-multiplatform-android/0.1.0/compose-multiplatform-android-0.1.0.module",
        "group": "com.highcapable.betterandroid",
        "module": "compose-multiplatform-android",
        "version": "0.1.0"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../compose-multiplatform-android/0.1.0/compose-multiplatform-android-0.1.0.module",
        "group": "com.highcapable.betterandroid",
        "module": "compose-multiplatform-android",
        "version": "0.1.0"
      }
    },
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../compose-multiplatform-desktop/0.1.0/compose-multiplatform-desktop-0.1.0.module",
        "group": "com.highcapable.betterandroid",
        "module": "compose-multiplatform-desktop",
        "version": "0.1.0"
      }
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../compose-multiplatform-desktop/0.1.0/compose-multiplatform-desktop-0.1.0.module",
        "group": "com.highcapable.betterandroid",
        "module": "compose-multiplatform-desktop",
        "version": "0.1.0"
      }
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../compose-multiplatform-desktop/0.1.0/compose-multiplatform-desktop-0.1.0.module",
        "group": "com.highcapable.betterandroid",
        "module": "compose-multiplatform-desktop",
        "version": "0.1.0"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../compose-multiplatform-iosarm64/0.1.0/compose-multiplatform-iosarm64-0.1.0.module",
        "group": "com.highcapable.betterandroid",
        "module": "compose-multiplatform-iosarm64",
        "version": "0.1.0"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../compose-multiplatform-iosarm64/0.1.0/compose-multiplatform-iosarm64-0.1.0.module",
        "group": "com.highcapable.betterandroid",
        "module": "compose-multiplatform-iosarm64",
        "version": "0.1.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../compose-multiplatform-iosarm64/0.1.0/compose-multiplatform-iosarm64-0.1.0.module",
        "group": "com.highcapable.betterandroid",
        "module": "compose-multiplatform-iosarm64",
        "version": "0.1.0"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../compose-multiplatform-iossimulatorarm64/0.1.0/compose-multiplatform-iossimulatorarm64-0.1.0.module",
        "group": "com.highcapable.betterandroid",
        "module": "compose-multiplatform-iossimulatorarm64",
        "version": "0.1.0"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../compose-multiplatform-iossimulatorarm64/0.1.0/compose-multiplatform-iossimulatorarm64-0.1.0.module",
        "group": "com.highcapable.betterandroid",
        "module": "compose-multiplatform-iossimulatorarm64",
        "version": "0.1.0"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../compose-multiplatform-iossimulatorarm64/0.1.0/compose-multiplatform-iossimulatorarm64-0.1.0.module",
        "group": "com.highcapable.betterandroid",
        "module": "compose-multiplatform-iossimulatorarm64",
        "version": "0.1.0"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../compose-multiplatform-iosx64/0.1.0/compose-multiplatform-iosx64-0.1.0.module",
        "group": "com.highcapable.betterandroid",
        "module": "compose-multiplatform-iosx64",
        "version": "0.1.0"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../compose-multiplatform-iosx64/0.1.0/compose-multiplatform-iosx64-0.1.0.module",
        "group": "com.highcapable.betterandroid",
        "module": "compose-multiplatform-iosx64",
        "version": "0.1.0"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../compose-multiplatform-iosx64/0.1.0/compose-multiplatform-iosx64-0.1.0.module",
        "group": "com.highcapable.betterandroid",
        "module": "compose-multiplatform-iosx64",
        "version": "0.1.0"
      }
    }
  ]
}
