{
  "formatVersion": "1.1",
  "component": {
    "group": "com.highcapable.pangutext",
    "module": "pangutext-android",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "pangutext-android-1.0.0.aar",
          "url": "pangutext-android-1.0.0.aar",
          "size": 45540,
          "sha512": "916adc82dd63ab007e7a59ac495214f646f0bd06803c04c8c2e508c1f54ee86913650ddd3bc43b8acb00aab6212889eadd6259183be3ca76d53bc8e44aedd344",
          "sha256": "13b28975da549a3ac8f2ba2f1a31bf12a32a4b329d3faa2a039e4e955a376ad3",
          "sha1": "eec0565fb8231152ae66c266b6a7f6d59936ab3b",
          "md5": "3d2a03a45aacc570e4f2c3bf09a81eaf"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.highcapable.yukireflection",
          "module": "api",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.highcapable.betterandroid",
          "module": "ui-extension",
          "version": {
            "requires": "1.0.5"
          }
        },
        {
          "group": "com.highcapable.betterandroid",
          "module": "system-extension",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "pangutext-android-1.0.0.aar",
          "url": "pangutext-android-1.0.0.aar",
          "size": 45540,
          "sha512": "916adc82dd63ab007e7a59ac495214f646f0bd06803c04c8c2e508c1f54ee86913650ddd3bc43b8acb00aab6212889eadd6259183be3ca76d53bc8e44aedd344",
          "sha256": "13b28975da549a3ac8f2ba2f1a31bf12a32a4b329d3faa2a039e4e955a376ad3",
          "sha1": "eec0565fb8231152ae66c266b6a7f6d59936ab3b",
          "md5": "3d2a03a45aacc570e4f2c3bf09a81eaf"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "pangutext-android-1.0.0-sources.jar",
          "url": "pangutext-android-1.0.0-sources.jar",
          "size": 20328,
          "sha512": "56cf191c0a1f4836b49ac5da52b724b055f7b002911c9bdf197cff3012f825f4dfaee2b4e787a69d900d67156a21bb626d1b1a09a44d0bae516346473a08837e",
          "sha256": "b7f4050439a65ed152d85250de24eeb30532233eacdbfb6d6095e22195c77d2c",
          "sha1": "ad7872ca0a669d744dada0785faf5f2866ff4e37",
          "md5": "636bcad047e6980f7593a54984c634c3"
        }
      ]
    }
  ]
}
