{
  "formatVersion": "1.1",
  "component": {
    "group": "com.highcapable.betterandroid",
    "module": "ui-component",
    "version": "1.0.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.9.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ui-component-1.0.8.aar",
          "url": "ui-component-1.0.8.aar",
          "size": 113779,
          "sha512": "af0db4f913c8004c49721c15f7373621d06d93de5d29cf4ad2778a7d74f6440731ce3fc97526771f11fac1325136abe7035af92bca7b57ac7fdd88fe12efa0dc",
          "sha256": "9eda20dc1ba07991ccd6ebbd896b529d72d72dcfadb57391e924a7694d31d478",
          "sha1": "9ee82288a17d7c0383ca3432f9eea0ed1fce842a",
          "md5": "a0c8f014f569c9d70d220de6df35f70c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.highcapable.betterandroid",
          "module": "ui-extension",
          "version": {
            "requires": "1.0.7"
          }
        },
        {
          "group": "com.highcapable.betterandroid",
          "module": "system-extension",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.highcapable.kavaref",
          "module": "kavaref-core",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.highcapable.kavaref",
          "module": "kavaref-extension",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.9.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ui-component-1.0.8.aar",
          "url": "ui-component-1.0.8.aar",
          "size": 113779,
          "sha512": "af0db4f913c8004c49721c15f7373621d06d93de5d29cf4ad2778a7d74f6440731ce3fc97526771f11fac1325136abe7035af92bca7b57ac7fdd88fe12efa0dc",
          "sha256": "9eda20dc1ba07991ccd6ebbd896b529d72d72dcfadb57391e924a7694d31d478",
          "sha1": "9ee82288a17d7c0383ca3432f9eea0ed1fce842a",
          "md5": "a0c8f014f569c9d70d220de6df35f70c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-component-1.0.8-sources.jar",
          "url": "ui-component-1.0.8-sources.jar",
          "size": 59528,
          "sha512": "648eeccc6ad6b7fb56961928ddc79e3f4213988033cf877cbcf06507d6c91b77ff4aea0347e5b911d72f1a1741cd97ecb50d8c0a7c23673fd5d169e09ad6c575",
          "sha256": "f7552bbf4cdac8d6979f6f9ab72e5a1f82f76bd406ffcbd954a919d795f07ce6",
          "sha1": "e00ba32f38be133f4239efe06f54eb196613308d",
          "md5": "642398c5e3140053097e0631ae1f3a8f"
        }
      ]
    }
  ]
}
