{
  "formatVersion": "1.1",
  "component": {
    "url": "../../resources/0.1.0-alpha01/resources-0.1.0-alpha01.module",
    "group": "com.highcapable.flexiui",
    "module": "resources",
    "version": "0.1.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.11"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.6.11"
          }
        },
        {
          "group": "com.highcapable.betterandroid",
          "module": "compose-extension",
          "version": {
            "requires": "1.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "flexiui-resources.klib",
          "url": "resources-iosx64-0.1.0-alpha01.klib",
          "size": 20260,
          "sha512": "67f334065d5dabc928ba26c8f6254554e842f279354274919056091fde5d94ddc9da95139fd3a1d4c3b18f8c93d148c000fec3dbbd9019f37eb64eba2f2bb89d",
          "sha256": "242b4b1aeda9276f5a9f5f80474271ac482156387b0f6256b5802f38970280b4",
          "sha1": "26dbf00fab0d9e9be91ff2e3d3dae3fca5a4fc2e",
          "md5": "a8df5b64563a63fdfd0e93f85ed05531"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "flexiui-resources-iosx64-0.1.0-alpha01-sources.jar",
          "url": "resources-iosx64-0.1.0-alpha01-sources.jar",
          "size": 11172,
          "sha512": "335fc250d8a967bd3276ff4e194c0c5f6b9d9cf714587cc9693776b952e0fb7c56610ffc82b45bda2b7cd73d3d93e373ecc09134b66e96c6176d12ebbaab60b0",
          "sha256": "cc71b9e792df702857e695bc1d3a024ff3a833977b32801eec972983646a8fcb",
          "sha1": "b2301fe22ae43d4481b7a3da224462e3ff3bb250",
          "md5": "61264f6e61ff6379e74bd37095942476"
        }
      ]
    },
    {
      "name": "iosX64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.11"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.6.11"
          }
        },
        {
          "group": "com.highcapable.betterandroid",
          "module": "compose-extension",
          "version": {
            "requires": "1.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "flexiui-resources-0.1.0-alpha01.kotlin_resources.zip",
          "url": "resources-iosx64-0.1.0-alpha01-kotlin_resources.kotlin_resources.zip",
          "size": 370,
          "sha512": "3139979a3e515c5a6386f3b0aac2d1242853fc1b59be28035044150f74e1576c16da5b86ef408e4d08a2a2ba84b4646cbede7a2a70c0ab8f7a4b32ac9c90290e",
          "sha256": "b3b8b8393222ac8fb06afdb6d4c9a8eb50c3efcc823cede841b9a06496dd337b",
          "sha1": "cfbcdcc129df1330beb7dbbf5d730ef2173c351c",
          "md5": "92908ed3a9ed25ba1e9266753045296d"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.11"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.6.11"
          }
        },
        {
          "group": "com.highcapable.betterandroid",
          "module": "compose-extension",
          "version": {
            "requires": "1.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "flexiui-resources-iosx64-0.1.0-alpha01-metadata.jar",
          "url": "resources-iosx64-0.1.0-alpha01-metadata.jar",
          "size": 261,
          "sha512": "db8b81385487e77a15261b628e33db39e98cc37aade14f7b1835ebc1fc5b976a43287192be0d107f19fa82411392ca71b7a53c684de5bb3fb1b10c3dc9ab58b7",
          "sha256": "d99e73300a456c9917f7cf726e2be0249b4641eb6cc44d599319952b6d0b6802",
          "sha1": "7ad9611dad67ab62c041f938ab36b48e92e13e39",
          "md5": "248c598abae40dbba31180c9d731b142"
        }
      ]
    }
  ]
}
