{
  "formatVersion": "1.1",
  "component": {
    "group": "com.highcapable.hikage",
    "module": "hikage-extension",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "hikage-extension-1.0.2.aar",
          "url": "hikage-extension-1.0.2.aar",
          "size": 21824,
          "sha512": "270f31a2213d144147049523d588623312d902249e491c2066542853cfddd4b54b5517660c6adbd3c2cab526f5ad6a2aa91931d7c74dcb6f954b89c1b0d14a9b",
          "sha256": "c438f87b0e7f243f1ae57423ce1cb60ca88e0227a0575885729e5935a3d16d18",
          "sha1": "4f30b64059fbd477ccafd0b9b8bd6046ba1eb2bb",
          "md5": "74325b182d51a462c0a402dbf212ab9f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.highcapable.hikage",
          "module": "hikage-core",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.highcapable.kavaref",
          "module": "kavaref-core",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "com.highcapable.kavaref",
          "module": "kavaref-extension",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "com.highcapable.betterandroid",
          "module": "ui-extension",
          "version": {
            "requires": "1.0.8"
          }
        },
        {
          "group": "com.highcapable.betterandroid",
          "module": "system-extension",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "hikage-extension-1.0.2.aar",
          "url": "hikage-extension-1.0.2.aar",
          "size": 21824,
          "sha512": "270f31a2213d144147049523d588623312d902249e491c2066542853cfddd4b54b5517660c6adbd3c2cab526f5ad6a2aa91931d7c74dcb6f954b89c1b0d14a9b",
          "sha256": "c438f87b0e7f243f1ae57423ce1cb60ca88e0227a0575885729e5935a3d16d18",
          "sha1": "4f30b64059fbd477ccafd0b9b8bd6046ba1eb2bb",
          "md5": "74325b182d51a462c0a402dbf212ab9f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "hikage-extension-1.0.2-sources.jar",
          "url": "hikage-extension-1.0.2-sources.jar",
          "size": 10082,
          "sha512": "d2888e682597638ca27af2ebf0f45db640ae1b76d3c776137b1b1b552f9d03063924891396e0e71902c2a61d6b5b77e026acd12b40448d65e72be9b442da5d91",
          "sha256": "aebaca25eb0bc33f563560fb46e932cbafc20b3365790842c9e836a446d45e54",
          "sha1": "06434ef82f2dfafdd0e2c7735758dfa2e248e6fc",
          "md5": "5b72a08f7bf37987484a653d77864074"
        }
      ]
    }
  ]
}
