{
  "formatVersion": "1.1",
  "component": {
    "group": "com.highcapable.betterandroid",
    "module": "compose-extension",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.5.11"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.5.11"
          }
        }
      ],
      "files": [
        {
          "name": "compose-extension-metadata-1.0.0.jar",
          "url": "compose-extension-1.0.0.jar",
          "size": 10757,
          "sha512": "3f44b1451626f7fe31c9569744c2c499d7ef4822a7dbd91816e52728a0ff1d54abcfca1eea0aea0a3bc0cd95b314c19ec41a0eb60f8bd1525384294a64f6d892",
          "sha256": "2cb59eee478fcc648489bcc02d0afe8c9aa5699a790c55ac3c8f47e8f43db2f7",
          "sha1": "c13a01370df7369aedc651115485f3daf640bbfc",
          "md5": "0edf0508d2b72ba6d0799cd315af15e3"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "compose-extension-kotlin-1.0.0-sources.jar",
          "url": "compose-extension-1.0.0-sources.jar",
          "size": 20401,
          "sha512": "b85b28326a7598f96c6b5050741a2a05dc6ecf6eb78e3e7950790d14429f1cd6293dc7245bb6d120da5e836646e4904041cb7dfc891b5854e79519275f2e7dc5",
          "sha256": "50d9e0c54ca053d92f03660117b60a306c991bda064cfcc0b92ce7e82d013f86",
          "sha1": "e5826cdf4ead9a80058803082cf4ddf05d8b7f61",
          "md5": "5e31b2f84be30aaceb75f5cbfc6943fb"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../compose-extension-android/1.0.0/compose-extension-android-1.0.0.module",
        "group": "com.highcapable.betterandroid",
        "module": "compose-extension-android",
        "version": "1.0.0"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../compose-extension-android/1.0.0/compose-extension-android-1.0.0.module",
        "group": "com.highcapable.betterandroid",
        "module": "compose-extension-android",
        "version": "1.0.0"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../compose-extension-android/1.0.0/compose-extension-android-1.0.0.module",
        "group": "com.highcapable.betterandroid",
        "module": "compose-extension-android",
        "version": "1.0.0"
      }
    },
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../compose-extension-desktop/1.0.0/compose-extension-desktop-1.0.0.module",
        "group": "com.highcapable.betterandroid",
        "module": "compose-extension-desktop",
        "version": "1.0.0"
      }
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../compose-extension-desktop/1.0.0/compose-extension-desktop-1.0.0.module",
        "group": "com.highcapable.betterandroid",
        "module": "compose-extension-desktop",
        "version": "1.0.0"
      }
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../compose-extension-desktop/1.0.0/compose-extension-desktop-1.0.0.module",
        "group": "com.highcapable.betterandroid",
        "module": "compose-extension-desktop",
        "version": "1.0.0"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../compose-extension-iosarm64/1.0.0/compose-extension-iosarm64-1.0.0.module",
        "group": "com.highcapable.betterandroid",
        "module": "compose-extension-iosarm64",
        "version": "1.0.0"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../compose-extension-iosarm64/1.0.0/compose-extension-iosarm64-1.0.0.module",
        "group": "com.highcapable.betterandroid",
        "module": "compose-extension-iosarm64",
        "version": "1.0.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../compose-extension-iosarm64/1.0.0/compose-extension-iosarm64-1.0.0.module",
        "group": "com.highcapable.betterandroid",
        "module": "compose-extension-iosarm64",
        "version": "1.0.0"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../compose-extension-iossimulatorarm64/1.0.0/compose-extension-iossimulatorarm64-1.0.0.module",
        "group": "com.highcapable.betterandroid",
        "module": "compose-extension-iossimulatorarm64",
        "version": "1.0.0"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../compose-extension-iossimulatorarm64/1.0.0/compose-extension-iossimulatorarm64-1.0.0.module",
        "group": "com.highcapable.betterandroid",
        "module": "compose-extension-iossimulatorarm64",
        "version": "1.0.0"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../compose-extension-iossimulatorarm64/1.0.0/compose-extension-iossimulatorarm64-1.0.0.module",
        "group": "com.highcapable.betterandroid",
        "module": "compose-extension-iossimulatorarm64",
        "version": "1.0.0"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../compose-extension-iosx64/1.0.0/compose-extension-iosx64-1.0.0.module",
        "group": "com.highcapable.betterandroid",
        "module": "compose-extension-iosx64",
        "version": "1.0.0"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../compose-extension-iosx64/1.0.0/compose-extension-iosx64-1.0.0.module",
        "group": "com.highcapable.betterandroid",
        "module": "compose-extension-iosx64",
        "version": "1.0.0"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../compose-extension-iosx64/1.0.0/compose-extension-iosx64-1.0.0.module",
        "group": "com.highcapable.betterandroid",
        "module": "compose-extension-iosx64",
        "version": "1.0.0"
      }
    }
  ]
}
