{
  "formatVersion": "1.1",
  "component": {
    "group": "com.highcapable.hikage",
    "module": "hikage-extension-compose",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "hikage-extension-compose-1.0.1.aar",
          "url": "hikage-extension-compose-1.0.1.aar",
          "size": 10087,
          "sha512": "938905e5dd84b79fe4aaeba3702e2de9e855e1e0fd39a46bc5c7ea8b8ea42b0006c201bd10ef911c0aa6c68ed1f2bd932ebccd95d9f6805c310dab6ca559771e",
          "sha256": "4ee92112ac1718aa13dd2f840ab407d76b4d3c8ebe69977c64cce1ea85ffa914",
          "sha1": "25ac4e5e2f63358ecc61c4bef9e5f77bcb172274",
          "md5": "23a3d9ef0324cca6a886d451b953c6a0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.highcapable.hikage",
          "module": "hikage-core",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.highcapable.kavaref",
          "module": "kavaref-core",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "com.highcapable.kavaref",
          "module": "kavaref-extension",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "com.highcapable.betterandroid",
          "module": "ui-extension",
          "version": {
            "requires": "1.0.8"
          }
        },
        {
          "group": "com.highcapable.betterandroid",
          "module": "system-extension",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "hikage-extension-compose-1.0.1.aar",
          "url": "hikage-extension-compose-1.0.1.aar",
          "size": 10087,
          "sha512": "938905e5dd84b79fe4aaeba3702e2de9e855e1e0fd39a46bc5c7ea8b8ea42b0006c201bd10ef911c0aa6c68ed1f2bd932ebccd95d9f6805c310dab6ca559771e",
          "sha256": "4ee92112ac1718aa13dd2f840ab407d76b4d3c8ebe69977c64cce1ea85ffa914",
          "sha1": "25ac4e5e2f63358ecc61c4bef9e5f77bcb172274",
          "md5": "23a3d9ef0324cca6a886d451b953c6a0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "hikage-extension-compose-1.0.1-sources.jar",
          "url": "hikage-extension-compose-1.0.1-sources.jar",
          "size": 5328,
          "sha512": "487a234fc25fc443472c0233fcf3ebe9d25f26aed3c3c69ca8f7cdf0d4b67d00a209452cda4225f6a5f28cdb31b4c8ac2052902cab60997a75900c2924dcb51b",
          "sha256": "04c94dd45a7f6fad4f36e063e3d59efa1afbaffb824ed279c291bdab34fef98e",
          "sha1": "e7e79053a92da7109efbe0a2696dcf489224abc6",
          "md5": "19c3e3a10df47cc6ea0bef06dd76eefd"
        }
      ]
    }
  ]
}
