{
  "formatVersion": "1.1",
  "component": {
    "group": "com.highcapable.betterandroid",
    "module": "system-extension",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "system-extension-1.0.2.aar",
          "url": "system-extension-1.0.2.aar",
          "size": 44279,
          "sha512": "ad12de67a90dd50289ce0637eba9acc5d9c8ce132772c26d317031280ebf6160e5f175b96e2a803db22bea0573245ca020285372ec356ec6331827ba5c9a6744",
          "sha256": "17480753c1da04d9ba564dfd1ceb504fb676a14954985e58e6ee2011378614cd",
          "sha1": "f33ecef3428297470549bfc49b4f81fa3e45d166",
          "md5": "e116c5a7f694c88f6494e9be120253c1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.highcapable.yukireflection",
          "module": "api",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "system-extension-1.0.2.aar",
          "url": "system-extension-1.0.2.aar",
          "size": 44279,
          "sha512": "ad12de67a90dd50289ce0637eba9acc5d9c8ce132772c26d317031280ebf6160e5f175b96e2a803db22bea0573245ca020285372ec356ec6331827ba5c9a6744",
          "sha256": "17480753c1da04d9ba564dfd1ceb504fb676a14954985e58e6ee2011378614cd",
          "sha1": "f33ecef3428297470549bfc49b4f81fa3e45d166",
          "md5": "e116c5a7f694c88f6494e9be120253c1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "system-extension-1.0.2-sources.jar",
          "url": "system-extension-1.0.2-sources.jar",
          "size": 18240,
          "sha512": "0908c5c2dfded24fb4fa0035f0264f2f2ef4633e5e0194f3283d7f8723ea60fcfbd088875759d578dbbf89f67603f5a149131cf3837ffb30659dbcdc55ce5d52",
          "sha256": "0f5fde81c21404fbda77a2700fbf32d2b718b42e8a29266f833cf0b970105203",
          "sha1": "60100acb4b5242c58e3c18436291df6659ae14b5",
          "md5": "ff422d22a153fdb05f1d8283f446ed86"
        }
      ]
    }
  ]
}
