{
  "formatVersion": "1.1",
  "component": {
    "url": "../../compose-extension/1.0.2/compose-extension-1.0.2.module",
    "group": "com.highcapable.betterandroid",
    "module": "compose-extension",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.5.11"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.5.11"
          }
        }
      ],
      "files": [
        {
          "name": "compose-extension.klib",
          "url": "compose-extension-iosarm64-1.0.2.klib",
          "size": 64132,
          "sha512": "5d1f0a3a6cdf0cf35aa6ab85e3c9b9d068469c10a285284a840dbf5a7dbe179653b0bfb0dd21dd90d169b52a9de5bd4ac5e0a1c2d5e1595f8035979286712f4c",
          "sha256": "401c6424ba86dd52c08f65142dafb938cbde388785b5ef8c05f8a238d8a6495d",
          "sha1": "d3c01fd26ff1dccc5b1aa094344d4ae8d00fa2b9",
          "md5": "2e59cdec68d482dfa0454813cfdc7f1a"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "compose-extension-iosarm64-1.0.2-sources.jar",
          "url": "compose-extension-iosarm64-1.0.2-sources.jar",
          "size": 25205,
          "sha512": "a245022f1ab5355a55bf293c946dc5ce8acc3b97f4b80beae2a435b2e613dd2a4b9299d9bc297582026e7fabecc2fa2a2d852b279c76111d3ed6376c90da5a85",
          "sha256": "b8da5a48d013363b624b1d406dd20e635a600a81d6b6ce7a3cdb8bc66b23b15f",
          "sha1": "5581bc8bf52a52c8bfc7b9b3fcf9676fb4f6207a",
          "md5": "95b81577efbd4a8663ab79fb9b7ae33a"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.5.11"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.5.11"
          }
        }
      ],
      "files": [
        {
          "name": "compose-extension-iosarm64-1.0.2-metadata.jar",
          "url": "compose-extension-iosarm64-1.0.2-metadata.jar",
          "size": 7892,
          "sha512": "0d4f8e322e3f48302672abe9dd683511c94c52b504615e30455c5c9c822ad648ef5e419dbde43c98a8ee7757a65c89e2713037b971b65c41ae384bbb797bc0ba",
          "sha256": "a612ac82e524be36983f29818fb1a7c598a8cac359015e1b65b0d9c6b89b3dc0",
          "sha1": "d7488b4a5d43a9024f40c202cce8f719ec87310f",
          "md5": "2da430a6b4eb0a189171ea6d218c0baf"
        }
      ]
    }
  ]
}
