{
  "formatVersion": "1.1",
  "component": {
    "group": "com.highcapable.betterandroid",
    "module": "ui-component",
    "version": "1.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.5.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "ui-component-1.0.6.aar",
          "url": "ui-component-1.0.6.aar",
          "size": 231099,
          "sha512": "aefb54d5194b65b2bdae74b3510e7cf36b554b236e94b16e53b13690360bd6e0f5172bd2a76ec0ba9c002a2ba9f1cf314cd745f0f3fd2a770802b1edf452baa4",
          "sha256": "5b90f77d7fc56c03e46207aad522ebc3f345e95f78f367f0b627f5b5ddf33b39",
          "sha1": "b04a2b223ffba0f8547adaeb6a5fdf515542f9a6",
          "md5": "c55c915ee6114627335be47869f52f73"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.highcapable.betterandroid",
          "module": "ui-extension",
          "version": {
            "requires": "1.0.5"
          }
        },
        {
          "group": "com.highcapable.betterandroid",
          "module": "system-extension",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "com.highcapable.yukireflection",
          "module": "api",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.5.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "ui-component-1.0.6.aar",
          "url": "ui-component-1.0.6.aar",
          "size": 231099,
          "sha512": "aefb54d5194b65b2bdae74b3510e7cf36b554b236e94b16e53b13690360bd6e0f5172bd2a76ec0ba9c002a2ba9f1cf314cd745f0f3fd2a770802b1edf452baa4",
          "sha256": "5b90f77d7fc56c03e46207aad522ebc3f345e95f78f367f0b627f5b5ddf33b39",
          "sha1": "b04a2b223ffba0f8547adaeb6a5fdf515542f9a6",
          "md5": "c55c915ee6114627335be47869f52f73"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-component-1.0.6-sources.jar",
          "url": "ui-component-1.0.6-sources.jar",
          "size": 98131,
          "sha512": "383736bf654c979f781c167bbd00b71c638e70e876d4138e0e1e8ce4d240a412ee0dbfe02b695b28c6c1ab8eb1fc04097952cc904c4bf32154a0b005fd5f677e",
          "sha256": "96c1d30803b98ebc8548df58ba23aa7604d0ee0a84189275ccfec5ddc6a47a61",
          "sha1": "e40b913dbe21b74982926e6f0bf4e0ef5819771c",
          "md5": "02e49b9fb9c3581f87bc4075ef30a5cd"
        }
      ]
    }
  ]
}
