{
  "formatVersion": "1.1",
  "component": {
    "group": "com.highcapable.hikage",
    "module": "hikage-compiler",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "hikage-compiler-1.0.1.jar",
          "url": "hikage-compiler-1.0.1.jar",
          "size": 49035,
          "sha512": "701bc0eeb1b1755d0153833ec3700a7e7934186bbb8c05fbe0dba6fa81ff17a4619e05380f39bd046fb55d4982808629cd52bec22dbb80e10dda0afc79781596",
          "sha256": "615c04f99850ed7d4ac2e7f62ae971689d14441fce3bf04c98e043220bedf848",
          "sha1": "fc302b371fe5cc3423c3b198ed66c2e886bd31fa",
          "md5": "1728ec46579624edd56da21d049e5047"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.auto.service",
          "module": "auto-service-annotations",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet-ksp",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "hikage-compiler-1.0.1.jar",
          "url": "hikage-compiler-1.0.1.jar",
          "size": 49035,
          "sha512": "701bc0eeb1b1755d0153833ec3700a7e7934186bbb8c05fbe0dba6fa81ff17a4619e05380f39bd046fb55d4982808629cd52bec22dbb80e10dda0afc79781596",
          "sha256": "615c04f99850ed7d4ac2e7f62ae971689d14441fce3bf04c98e043220bedf848",
          "sha1": "fc302b371fe5cc3423c3b198ed66c2e886bd31fa",
          "md5": "1728ec46579624edd56da21d049e5047"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "hikage-compiler-1.0.1-sources.jar",
          "url": "hikage-compiler-1.0.1-sources.jar",
          "size": 12254,
          "sha512": "ae5c810b2d4ba46e509bb35b34754136a2f3b503bed730dd2918049b29a73471a85558a6d2f4bf421e8bcc6c99df1a3a7872fa95ba1f643489b27c43d72ca6f9",
          "sha256": "254fbc6878a3061d49bbcb2e9e230a41e52109974ef98686e16e6bb5665e0f6f",
          "sha1": "7e99b83c57d9d081044ddabde8ec0d9acdc65461",
          "md5": "d5786d9fee45dbd339c43c7b7343beb9"
        }
      ]
    }
  ]
}
