{
  "formatVersion": "1.1",
  "component": {
    "group": "com.highcapable.betterandroid",
    "module": "ui-extension",
    "version": "1.1.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "9.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "ui-extension-1.1.6.aar",
          "url": "ui-extension-1.1.6.aar",
          "size": 390626,
          "sha512": "638a4fb7cc3529e1c56f7c3d934201bafb48fb597669dd053384ef114c8a928199db6acf8ae53b48f5a031d626befcf5a698feb71af5a9f93f38ac7142a3af15",
          "sha256": "a54478d697acd5ae09a1c446ddc617a2626359fd9a2d550b77a65ecca3d11559",
          "sha1": "316587182c839f8996c8cc0cddbcbd1fb592767c",
          "md5": "f6f18b012c1037c38d95dbbfaef7d1a5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.highcapable.betterandroid",
          "module": "system-extension",
          "version": {
            "requires": "1.1.6"
          }
        },
        {
          "group": "com.highcapable.kavaref",
          "module": "kavaref-bom",
          "version": {
            "requires": "1.1.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.highcapable.kavaref",
          "module": "kavaref-core"
        },
        {
          "group": "com.highcapable.kavaref",
          "module": "kavaref-android"
        },
        {
          "group": "com.highcapable.kavaref",
          "module": "kavaref-extension"
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.19.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "9.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "ui-extension-1.1.6.aar",
          "url": "ui-extension-1.1.6.aar",
          "size": 390626,
          "sha512": "638a4fb7cc3529e1c56f7c3d934201bafb48fb597669dd053384ef114c8a928199db6acf8ae53b48f5a031d626befcf5a698feb71af5a9f93f38ac7142a3af15",
          "sha256": "a54478d697acd5ae09a1c446ddc617a2626359fd9a2d550b77a65ecca3d11559",
          "sha1": "316587182c839f8996c8cc0cddbcbd1fb592767c",
          "md5": "f6f18b012c1037c38d95dbbfaef7d1a5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-extension-1.1.6-sources.jar",
          "url": "ui-extension-1.1.6-sources.jar",
          "size": 60613,
          "sha512": "39616ab72960fb81e08f6d4c9580e0c3b77fa9e25a538edd852cb8ce7641a62aa6a41e18266b4ba6fc49c924f9afe1fd285218f9fccae8d8cc6bf7afe1296cf3",
          "sha256": "c4f4b9fe07a5c5e552395a8ae156a07134fffc901d9911323ddcb2368b5a9441",
          "sha1": "372910a5a1b2465bfd3043411b575be47610f7e1",
          "md5": "6c83e54eab0fb36ef1adbc33a5546732"
        }
      ]
    }
  ]
}
