{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.1.0-alpha01-dev0006/core-0.1.0-alpha01-dev0006.module",
    "group": "com.highcapable.flexiui",
    "module": "core",
    "version": "0.1.0-alpha01-dev0006",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.5.11"
          }
        },
        {
          "group": "com.highcapable.flexiui",
          "module": "resources",
          "version": {
            "requires": "0.1.0-alpha01"
          }
        },
        {
          "group": "com.highcapable.betterandroid",
          "module": "compose-extension",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        }
      ],
      "files": [
        {
          "name": "flexiui-core-desktop-0.1.0-alpha01-dev0006.jar",
          "url": "core-desktop-0.1.0-alpha01-dev0006.jar",
          "size": 1021746,
          "sha512": "f97f5cc3f0bfce81c18e5f82962dd9e57002a536f0dda74e2a3ae8f0b354329a7311e85560d71e77f87ab006c8c8bd23ba95d7049c1dc0ea431061e1369396ed",
          "sha256": "ed6ad82e83192291744c5cd4c16c78df8a51e7a0e545bd052baeacffab23ac8c",
          "sha1": "0e2477f70534928edbf9cf506d40cc5147f6abd8",
          "md5": "dccb39090c0089a2b9abe8dcb7e2e936"
        }
      ]
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.5.11"
          }
        },
        {
          "group": "com.highcapable.flexiui",
          "module": "resources",
          "version": {
            "requires": "0.1.0-alpha01"
          }
        },
        {
          "group": "com.highcapable.betterandroid",
          "module": "compose-extension",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.5.11"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-ripple",
          "version": {
            "requires": "1.5.11"
          }
        }
      ],
      "files": [
        {
          "name": "flexiui-core-desktop-0.1.0-alpha01-dev0006.jar",
          "url": "core-desktop-0.1.0-alpha01-dev0006.jar",
          "size": 1021746,
          "sha512": "f97f5cc3f0bfce81c18e5f82962dd9e57002a536f0dda74e2a3ae8f0b354329a7311e85560d71e77f87ab006c8c8bd23ba95d7049c1dc0ea431061e1369396ed",
          "sha256": "ed6ad82e83192291744c5cd4c16c78df8a51e7a0e545bd052baeacffab23ac8c",
          "sha1": "0e2477f70534928edbf9cf506d40cc5147f6abd8",
          "md5": "dccb39090c0089a2b9abe8dcb7e2e936"
        }
      ]
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "flexiui-core-desktop-0.1.0-alpha01-dev0006-sources.jar",
          "url": "core-desktop-0.1.0-alpha01-dev0006-sources.jar",
          "size": 90958,
          "sha512": "0d3faa6965af166e0bfe1b025f1c29e5768c580244739d1f278cb8658106aa4796befcf4dae87a626078a9cd29c8edf38c853a2b544174d19888ef37efa52cb5",
          "sha256": "6f406b9f6e7517a799a8c02cfbea28b06ab044aecef974f0b0602188559b6caf",
          "sha1": "ff08f1655235f7c5180f91b384adcc6a69833eb7",
          "md5": "8c62a73e0d95cc36398a8e757d15cbf7"
        }
      ]
    }
  ]
}
