{
  "formatVersion": "1.1",
  "component": {
    "group": "com.highcapable.betterandroid",
    "module": "system-extension",
    "version": "1.1.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "system-extension-1.1.5.aar",
          "url": "system-extension-1.1.5.aar",
          "size": 148479,
          "sha512": "bf6104163832c2366d773b6a028172963ed6ec112d2177fb599fb3717ed7b6a7b42695cf200b2a6376ae8d4ecf0eeb4ff35e75daa5260bda6818219813ca0c5a",
          "sha256": "63e4305f973bebb3c45656357f90fc141ca96c3bda11cdad51466b6ab8e1f876",
          "sha1": "e48e279c5725f43c42da2c48c3efcac6e69d194e",
          "md5": "0e81a96f8290fe52523dac8a4bd332cb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.highcapable.kavaref",
          "module": "kavaref-bom",
          "version": {
            "requires": "1.1.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.highcapable.kavaref",
          "module": "kavaref-core"
        },
        {
          "group": "com.highcapable.kavaref",
          "module": "kavaref-android"
        },
        {
          "group": "com.highcapable.kavaref",
          "module": "kavaref-extension"
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "system-extension-1.1.5.aar",
          "url": "system-extension-1.1.5.aar",
          "size": 148479,
          "sha512": "bf6104163832c2366d773b6a028172963ed6ec112d2177fb599fb3717ed7b6a7b42695cf200b2a6376ae8d4ecf0eeb4ff35e75daa5260bda6818219813ca0c5a",
          "sha256": "63e4305f973bebb3c45656357f90fc141ca96c3bda11cdad51466b6ab8e1f876",
          "sha1": "e48e279c5725f43c42da2c48c3efcac6e69d194e",
          "md5": "0e81a96f8290fe52523dac8a4bd332cb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "system-extension-1.1.5-sources.jar",
          "url": "system-extension-1.1.5-sources.jar",
          "size": 21287,
          "sha512": "5ebec22b8375ced22a84cfc3e2c2960a1823c9fa1cdd005d771a5ef914a74cfe70be0fe83616bb93d1e7c86824a153e105957b19d9ada2aa6be1d471c325e5e0",
          "sha256": "1343ad36c65d00f7842af17192205f6656cd7f703fbacc64ebe2beece463e90f",
          "sha1": "5503877dd86c7ad3aec25c0b7ecbdc517d45053c",
          "md5": "a1ba8cef8f7d9c73ea8469cc537bf2da"
        }
      ]
    }
  ]
}
