{
  "formatVersion": "1.1",
  "component": {
    "group": "com.highcapable.hikage",
    "module": "hikage-extension-compose",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "hikage-extension-compose-1.0.0.aar",
          "url": "hikage-extension-compose-1.0.0.aar",
          "size": 12612,
          "sha512": "fd5d2f2cd24a3ff805a4c830a479fb1f5a22e24a9bf6ab1173d227a45fed0866eae03c3cc1d66fcf7a8a60b9c1ff357b0c9d620a054c890ff930196040e2470e",
          "sha256": "f7c7c679488f40fc9bcab52f1afa6cb90c52ecef7fa9a0eedf4704ecce9bc014",
          "sha1": "9093363868bf7ffc48d1341af76cece1e7e63113",
          "md5": "bc224913c591161b182c5a7f3e76dac3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.highcapable.hikage",
          "module": "hikage-core",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.highcapable.yukireflection",
          "module": "api",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.highcapable.betterandroid",
          "module": "ui-extension",
          "version": {
            "requires": "1.0.6"
          }
        },
        {
          "group": "com.highcapable.betterandroid",
          "module": "system-extension",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.8"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "hikage-extension-compose-1.0.0.aar",
          "url": "hikage-extension-compose-1.0.0.aar",
          "size": 12612,
          "sha512": "fd5d2f2cd24a3ff805a4c830a479fb1f5a22e24a9bf6ab1173d227a45fed0866eae03c3cc1d66fcf7a8a60b9c1ff357b0c9d620a054c890ff930196040e2470e",
          "sha256": "f7c7c679488f40fc9bcab52f1afa6cb90c52ecef7fa9a0eedf4704ecce9bc014",
          "sha1": "9093363868bf7ffc48d1341af76cece1e7e63113",
          "md5": "bc224913c591161b182c5a7f3e76dac3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "hikage-extension-compose-1.0.0-sources.jar",
          "url": "hikage-extension-compose-1.0.0-sources.jar",
          "size": 5410,
          "sha512": "c03ba498ffe5030dcf77d7a0ee2e647b180232019a48d2aa023d987d69f8cc817d8cbb534229ba94687ae30672f90eb8f6395c9369d577b1422568a9d394fd52",
          "sha256": "1e82ea6445cf38cadc4fa30385250b6b63829c7a6d5c94d61a3f78deb9844556",
          "sha1": "afec55e8953be47dac47005dbd246ff883eaefe3",
          "md5": "4242d5d2a2fbfa438034bf2bc1c2b106"
        }
      ]
    }
  ]
}
