{
  "formatVersion": "1.1",
  "component": {
    "group": "com.highcapable.betterandroid",
    "module": "compose-extension",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.5.11"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.5.11"
          }
        }
      ],
      "files": [
        {
          "name": "compose-extension-metadata-1.0.2.jar",
          "url": "compose-extension-1.0.2.jar",
          "size": 11815,
          "sha512": "73b9b18fb0031752cba011fd8b0acfe665e33210da6c46b86d61201007bd1b25352663fb5d48602a87a29932e9aeba6d2c5ee356dbd2a5018833c59948040bc6",
          "sha256": "2a94b1d373ca54d48c2356f6bfb9e8b72016f0254560c81e1236d695135a08fb",
          "sha1": "0fab8906bc7a38f7eada4082463e794ab768eda2",
          "md5": "f5b8bd644c0e6e252025f868048e590d"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "compose-extension-kotlin-1.0.2-sources.jar",
          "url": "compose-extension-1.0.2-sources.jar",
          "size": 22971,
          "sha512": "546355674e2d33275ad9fc437d0724a6e7c20cd9e759a49e7be44c9597a6e074602fe6561149616334675023f4904fabe90ca2b4f169b6700c938ec165914de3",
          "sha256": "74ab0fe1bf824a3f83928a34c996424148e15aa97edbe5a71245acc3106af2e0",
          "sha1": "d297bcd37ef8e284ef4daa666b463118de72f9ae",
          "md5": "92fa0147dd7a818db73d8da1d25d938d"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../compose-extension-android/1.0.2/compose-extension-android-1.0.2.module",
        "group": "com.highcapable.betterandroid",
        "module": "compose-extension-android",
        "version": "1.0.2"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../compose-extension-android/1.0.2/compose-extension-android-1.0.2.module",
        "group": "com.highcapable.betterandroid",
        "module": "compose-extension-android",
        "version": "1.0.2"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../compose-extension-android/1.0.2/compose-extension-android-1.0.2.module",
        "group": "com.highcapable.betterandroid",
        "module": "compose-extension-android",
        "version": "1.0.2"
      }
    },
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../compose-extension-desktop/1.0.2/compose-extension-desktop-1.0.2.module",
        "group": "com.highcapable.betterandroid",
        "module": "compose-extension-desktop",
        "version": "1.0.2"
      }
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../compose-extension-desktop/1.0.2/compose-extension-desktop-1.0.2.module",
        "group": "com.highcapable.betterandroid",
        "module": "compose-extension-desktop",
        "version": "1.0.2"
      }
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../compose-extension-desktop/1.0.2/compose-extension-desktop-1.0.2.module",
        "group": "com.highcapable.betterandroid",
        "module": "compose-extension-desktop",
        "version": "1.0.2"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../compose-extension-iosarm64/1.0.2/compose-extension-iosarm64-1.0.2.module",
        "group": "com.highcapable.betterandroid",
        "module": "compose-extension-iosarm64",
        "version": "1.0.2"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../compose-extension-iosarm64/1.0.2/compose-extension-iosarm64-1.0.2.module",
        "group": "com.highcapable.betterandroid",
        "module": "compose-extension-iosarm64",
        "version": "1.0.2"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../compose-extension-iosarm64/1.0.2/compose-extension-iosarm64-1.0.2.module",
        "group": "com.highcapable.betterandroid",
        "module": "compose-extension-iosarm64",
        "version": "1.0.2"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../compose-extension-iossimulatorarm64/1.0.2/compose-extension-iossimulatorarm64-1.0.2.module",
        "group": "com.highcapable.betterandroid",
        "module": "compose-extension-iossimulatorarm64",
        "version": "1.0.2"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../compose-extension-iossimulatorarm64/1.0.2/compose-extension-iossimulatorarm64-1.0.2.module",
        "group": "com.highcapable.betterandroid",
        "module": "compose-extension-iossimulatorarm64",
        "version": "1.0.2"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../compose-extension-iossimulatorarm64/1.0.2/compose-extension-iossimulatorarm64-1.0.2.module",
        "group": "com.highcapable.betterandroid",
        "module": "compose-extension-iossimulatorarm64",
        "version": "1.0.2"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../compose-extension-iosx64/1.0.2/compose-extension-iosx64-1.0.2.module",
        "group": "com.highcapable.betterandroid",
        "module": "compose-extension-iosx64",
        "version": "1.0.2"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../compose-extension-iosx64/1.0.2/compose-extension-iosx64-1.0.2.module",
        "group": "com.highcapable.betterandroid",
        "module": "compose-extension-iosx64",
        "version": "1.0.2"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../compose-extension-iosx64/1.0.2/compose-extension-iosx64-1.0.2.module",
        "group": "com.highcapable.betterandroid",
        "module": "compose-extension-iosx64",
        "version": "1.0.2"
      }
    }
  ]
}
