{
  "formatVersion": "1.1",
  "component": {
    "group": "com.highcapable.betterandroid",
    "module": "ui-extension",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "ui-extension-1.0.3.aar",
          "url": "ui-extension-1.0.3.aar",
          "size": 106434,
          "sha512": "67061d6ffdd079a9ffe881f8b6ef74d023a64d3adb5893ba609752f302b95f6dd12b72e7addc117eccd08dd1f72fb7b3452d3739103e46989b5f4365082eb082",
          "sha256": "cf21010b8d111e713b0d58a24a5542de26491ef9960a90ce3d4178b61a0bf871",
          "sha1": "dde56ab59e7fcf679951ce0ddaf06353268f6abe",
          "md5": "d8ac2472b03eac376a653eb8d518d40d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.highcapable.betterandroid",
          "module": "system-extension",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.highcapable.yukireflection",
          "module": "api",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "ui-extension-1.0.3.aar",
          "url": "ui-extension-1.0.3.aar",
          "size": 106434,
          "sha512": "67061d6ffdd079a9ffe881f8b6ef74d023a64d3adb5893ba609752f302b95f6dd12b72e7addc117eccd08dd1f72fb7b3452d3739103e46989b5f4365082eb082",
          "sha256": "cf21010b8d111e713b0d58a24a5542de26491ef9960a90ce3d4178b61a0bf871",
          "sha1": "dde56ab59e7fcf679951ce0ddaf06353268f6abe",
          "md5": "d8ac2472b03eac376a653eb8d518d40d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-extension-1.0.3-sources.jar",
          "url": "ui-extension-1.0.3-sources.jar",
          "size": 39217,
          "sha512": "35b4567e10e0174b47e31b713a15723e58e30e9498df72894cc05fe6d6583c3f07d74e82e39e25666196de56cd74cd20fd6c58ba9e9b85c776c22a532f365691",
          "sha256": "1d2bcbb87ef42f95ddbd968e1610d3923f51fb1bb0e89b000a823279c551e3c2",
          "sha1": "c7549534d70624688e7aab1fe66d9b4e50760abd",
          "md5": "2479945fca8034353e75dd5f20c6fbc4"
        }
      ]
    }
  ]
}
