{
  "formatVersion": "1.1",
  "component": {
    "group": "com.highcapable.hikage",
    "module": "hikage-core",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.highcapable.betterandroid",
          "module": "ui-extension",
          "version": {
            "requires": "1.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "hikage-core-1.0.2.aar",
          "url": "hikage-core-1.0.2.aar",
          "size": 344609,
          "sha512": "63034b67219f4ddec8716df05697fc549c34104e47c53052ff608f463d2b3e3f6fb7e00c94ed9d15c678b2784c80fdbb11bfafa5c00230ab2a5ec6df78c40de6",
          "sha256": "7b32458ed956b822b8d5c9320c269a35e39c05bd481e248ed7d4a4ce883d52dd",
          "sha1": "1433a8bfaa9f5094c76979b7a1db01bb0a99e2bb",
          "md5": "73857c3e9bea1514756e21156e2159cf"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.lsposed.hiddenapibypass",
          "module": "hiddenapibypass",
          "version": {
            "requires": "6.1"
          }
        },
        {
          "group": "com.highcapable.kavaref",
          "module": "kavaref-core",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.highcapable.kavaref",
          "module": "kavaref-extension",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.highcapable.betterandroid",
          "module": "system-extension",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.highcapable.betterandroid",
          "module": "ui-extension",
          "version": {
            "requires": "1.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "hikage-core-1.0.2.aar",
          "url": "hikage-core-1.0.2.aar",
          "size": 344609,
          "sha512": "63034b67219f4ddec8716df05697fc549c34104e47c53052ff608f463d2b3e3f6fb7e00c94ed9d15c678b2784c80fdbb11bfafa5c00230ab2a5ec6df78c40de6",
          "sha256": "7b32458ed956b822b8d5c9320c269a35e39c05bd481e248ed7d4a4ce883d52dd",
          "sha1": "1433a8bfaa9f5094c76979b7a1db01bb0a99e2bb",
          "md5": "73857c3e9bea1514756e21156e2159cf"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "hikage-core-1.0.2-sources.jar",
          "url": "hikage-core-1.0.2-sources.jar",
          "size": 66552,
          "sha512": "a5fe9b3b97a61e3af0a7fb0a08caf44c32e2b16e9d2d7590b7c5fe0dc55039e54f5367cc53efea92a06dfbfa975997599148204742ecf1afe8e4391e26d24723",
          "sha256": "6c58369b7edb61dfad83a5ea07ba56e25938606236ed256e7b22ec22426b6603",
          "sha1": "fdc98d2685691ac5c2d3964a058be1e33ce22191",
          "md5": "5490fee117273307f046d769d08bf419"
        }
      ]
    }
  ]
}
