{
  "formatVersion": "1.1",
  "component": {
    "group": "com.highcapable.betterandroid",
    "module": "ui-extension",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.1.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "ui-extension-1.0.0.aar",
          "url": "ui-extension-1.0.0.aar",
          "size": 79257,
          "sha512": "ce90c7534ba2ce137e47b38508a1cc5c901d0146cf13016258763ad4d6805b5983e522e4192dc0cf897c658daaa411a28a1fc9c8279c71bc16820ed27cc91c21",
          "sha256": "edcc938949e2d6e23970b0709192aa91f5985c161cbe91545cf0b22d849d80d2",
          "sha1": "b367e35ea5335bbf7a9206ae57d940722dba51eb",
          "md5": "9fc2b3eb48cafbfa7e3c77424963564d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.highcapable.betterandroid",
          "module": "system-extension",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.highcapable.yukireflection",
          "module": "api",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.1.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "ui-extension-1.0.0.aar",
          "url": "ui-extension-1.0.0.aar",
          "size": 79257,
          "sha512": "ce90c7534ba2ce137e47b38508a1cc5c901d0146cf13016258763ad4d6805b5983e522e4192dc0cf897c658daaa411a28a1fc9c8279c71bc16820ed27cc91c21",
          "sha256": "edcc938949e2d6e23970b0709192aa91f5985c161cbe91545cf0b22d849d80d2",
          "sha1": "b367e35ea5335bbf7a9206ae57d940722dba51eb",
          "md5": "9fc2b3eb48cafbfa7e3c77424963564d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-extension-1.0.0-sources.jar",
          "url": "ui-extension-1.0.0-sources.jar",
          "size": 32177,
          "sha512": "732342149f7f737927afc9b2c749dc707e7e893d0bfbb4c73e97973515a94a1cdf03f2135fd261a3847e02ee0354bd47d3ec368c0115b258bf94e34ac8e18894",
          "sha256": "49a6be635f556c9063516662bac27a09c7669919edbff9cb48f2c933aa0ec0b6",
          "sha1": "91bfbdbfebb826db3f5826644b627387178c222e",
          "md5": "ffbc81fe2186386caf8591ef6f6a938a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-extension-1.0.0-javadoc.jar",
          "url": "ui-extension-1.0.0-javadoc.jar",
          "size": 389026,
          "sha512": "8c778c89052f9dfc447428e08cd874887451d97620ca34f7100ce2e97a7e88ea48b5e4024b98dc3f695332ff0b1e779efe2180680469838018573bed5b8dec0f",
          "sha256": "5bc264192beb62d3a4daf87e979488ca2cc25b6c68c291f69198995062a61b16",
          "sha1": "953f659843058a4f6e31dffe0e64294e72cd1305",
          "md5": "c35029f3e057156bce3df03f3f153ce1"
        }
      ]
    }
  ]
}
