{
  "formatVersion": "1.1",
  "component": {
    "group": "com.highcapable.betterandroid",
    "module": "ui-extension",
    "version": "1.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.8.5"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.5.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "ui-extension-1.0.6.aar",
          "url": "ui-extension-1.0.6.aar",
          "size": 128502,
          "sha512": "a1457abd7d68b915c9058d4026b5e2c4f146227cabc3df32697c6dcf591474bf56c9976751f1a19aabf46790d2c608abce3e81ccba6242660bffc5755955c2a4",
          "sha256": "87fb0c591af436478ab530178abbd7cac809c09fd1dc9c03a16f54c9b2ed20be",
          "sha1": "e55ed29027d9cc192edc7449dbae7c22b678e2f7",
          "md5": "ceaeb4d0b5f6a766f1583ec8967b79c9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.highcapable.betterandroid",
          "module": "system-extension",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "com.highcapable.yukireflection",
          "module": "api",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.8.5"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.5.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "ui-extension-1.0.6.aar",
          "url": "ui-extension-1.0.6.aar",
          "size": 128502,
          "sha512": "a1457abd7d68b915c9058d4026b5e2c4f146227cabc3df32697c6dcf591474bf56c9976751f1a19aabf46790d2c608abce3e81ccba6242660bffc5755955c2a4",
          "sha256": "87fb0c591af436478ab530178abbd7cac809c09fd1dc9c03a16f54c9b2ed20be",
          "sha1": "e55ed29027d9cc192edc7449dbae7c22b678e2f7",
          "md5": "ceaeb4d0b5f6a766f1583ec8967b79c9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-extension-1.0.6-sources.jar",
          "url": "ui-extension-1.0.6-sources.jar",
          "size": 45838,
          "sha512": "212991b2042d152032150261f2425d85e3e20a8a01bafef4cb50b9f7f1a04e4890f2ac4f54382f499887b934d9256c77042db0996b57f4bb87b23dcfd63bd0e5",
          "sha256": "1baf5b03661e92408eb7146ccdc512c6923e9028a2d37827188f69497ebe9cf7",
          "sha1": "de00c8cca44bbfb557238a3c6c88cf36b2e92694",
          "md5": "9c6d5a74ff745eacda720090f932f842"
        }
      ]
    }
  ]
}
