{
  "formatVersion": "1.1",
  "component": {
    "url": "../../resources/0.1.0-alpha01/resources-0.1.0-alpha01.module",
    "group": "com.highcapable.flexiui",
    "module": "resources",
    "version": "0.1.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.11"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.6.11"
          }
        },
        {
          "group": "com.highcapable.betterandroid",
          "module": "compose-extension",
          "version": {
            "requires": "1.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "flexiui-resources.klib",
          "url": "resources-iosarm64-0.1.0-alpha01.klib",
          "size": 20276,
          "sha512": "9d5a6af76ccaf802d467f523897bce71ef014ca3be661ffc81993c4712e9523e93ba54a35829d70d242f3b63591095a1bae739b5ba1c8911dc5ecf5ea330a6ed",
          "sha256": "e0c30796137ce00eb8ccef6d106b464ccfcaf482cfb0c1460a9b5896f8d58caa",
          "sha1": "d7f39309bf667f0f27a0478b5c8da33d6748b2f7",
          "md5": "b972df9bee2204bd98084ad57689568e"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "flexiui-resources-iosarm64-0.1.0-alpha01-sources.jar",
          "url": "resources-iosarm64-0.1.0-alpha01-sources.jar",
          "size": 11172,
          "sha512": "335fc250d8a967bd3276ff4e194c0c5f6b9d9cf714587cc9693776b952e0fb7c56610ffc82b45bda2b7cd73d3d93e373ecc09134b66e96c6176d12ebbaab60b0",
          "sha256": "cc71b9e792df702857e695bc1d3a024ff3a833977b32801eec972983646a8fcb",
          "sha1": "b2301fe22ae43d4481b7a3da224462e3ff3bb250",
          "md5": "61264f6e61ff6379e74bd37095942476"
        }
      ]
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.11"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.6.11"
          }
        },
        {
          "group": "com.highcapable.betterandroid",
          "module": "compose-extension",
          "version": {
            "requires": "1.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "flexiui-resources-0.1.0-alpha01.kotlin_resources.zip",
          "url": "resources-iosarm64-0.1.0-alpha01-kotlin_resources.kotlin_resources.zip",
          "size": 370,
          "sha512": "6cb9915b772920dc5256be0c1636eba3515b1b4cd7fe9055f8139c4d3c29376abc3e56e63ed16c67aca0c7bb0288f70d40bf036ee55119626bd4284c53f89d9c",
          "sha256": "79c7d44b8e85b1f1e3a32cac56c6b6c21f184ae950d4635dbb8fe919df9a98d7",
          "sha1": "c038b08e00ce0824235858795ec835daa718dc0b",
          "md5": "96a70367034c5d252c7577505797c51c"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.11"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.6.11"
          }
        },
        {
          "group": "com.highcapable.betterandroid",
          "module": "compose-extension",
          "version": {
            "requires": "1.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "flexiui-resources-iosarm64-0.1.0-alpha01-metadata.jar",
          "url": "resources-iosarm64-0.1.0-alpha01-metadata.jar",
          "size": 261,
          "sha512": "68ed9786b8f10c12ff46c34c4a9c039e6ddc1ea69c1d628c2ae6542e846b25cb3789065237fb40d56312d5de9997ea3a2f5b0809f6167e885d5798df8d335c79",
          "sha256": "374ee3268ce94487cfdd94316c502c438e1e23f0f1cc67a05797baa7a0af9abd",
          "sha1": "937bcb782f1c9725cfc9aa198b3632211dabe439",
          "md5": "7e4d0a9ffa65025ed89a024c812cab81"
        }
      ]
    }
  ]
}
