{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.1.0-alpha01-dev0005/core-0.1.0-alpha01-dev0005.module",
    "group": "com.highcapable.flexiui",
    "module": "core",
    "version": "0.1.0-alpha01-dev0005",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.5.11"
          }
        },
        {
          "group": "com.highcapable.flexiui",
          "module": "resources",
          "version": {
            "requires": "0.1.0-alpha01"
          }
        },
        {
          "group": "com.highcapable.betterandroid",
          "module": "compose-extension",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.5.11"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-ripple",
          "version": {
            "requires": "1.5.11"
          }
        }
      ],
      "files": [
        {
          "name": "flexiui-core.klib",
          "url": "core-iossimulatorarm64-0.1.0-alpha01-dev0005.klib",
          "size": 599518,
          "sha512": "06c1e8e9d3a21851267098b1742a91582254afd865ea09fab3d8fd93ac0d07dc017a1b7eb4210503a490ae2f2e547fafe27e05c04b06a05e92c691bc970448a0",
          "sha256": "85dbcd51089125069ccc8f0927bd9884681b6d979daae6d28af2a85755d1719f",
          "sha1": "cec6f34e249274aaa8ec2d64d42897713ea30da5",
          "md5": "d75c147513eb083751318c0f619477a4"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "flexiui-core-iossimulatorarm64-0.1.0-alpha01-dev0005-sources.jar",
          "url": "core-iossimulatorarm64-0.1.0-alpha01-dev0005-sources.jar",
          "size": 89638,
          "sha512": "32fdc64be7beca3c5e4b483efb5fe5978dee35047f840931d9715e3bcc4b0489cdd97b516afdd221f09f1b57672cce481881cc1d3c56f822e1e31f0108550ee7",
          "sha256": "e76758946e28ee1da8815f6a6ab457e21ee49fec2a82ab898fa350dc2f67ca6c",
          "sha1": "35fc97c31a30f6152b52ca76cbc7f75956afd082",
          "md5": "5dc99b2357bc7b1d0332486a307f4746"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.5.11"
          }
        },
        {
          "group": "com.highcapable.flexiui",
          "module": "resources",
          "version": {
            "requires": "0.1.0-alpha01"
          }
        },
        {
          "group": "com.highcapable.betterandroid",
          "module": "compose-extension",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.5.11"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-ripple",
          "version": {
            "requires": "1.5.11"
          }
        }
      ],
      "files": [
        {
          "name": "flexiui-core-iossimulatorarm64-0.1.0-alpha01-dev0005-metadata.jar",
          "url": "core-iossimulatorarm64-0.1.0-alpha01-dev0005-metadata.jar",
          "size": 6819,
          "sha512": "59879f7d1b2eacbe2088aa6522e24fa31d05c50c8a5ff85d8509db2988fa2188b6807a500145d641ed0c7c6888ccd2b4b7652081772ab18eb2a40eac86a8aa20",
          "sha256": "8d72eddb35af87abf3c97ff6eb4b4d1bf7c92cb117cd672c5af09a213f73f46a",
          "sha1": "36fb23025cfde61894576fcfdb0b69cd469c8771",
          "md5": "21c6edd5e687210c4edd735cdb360df2"
        }
      ]
    }
  ]
}
