{
  "formatVersion": "1.1",
  "component": {
    "group": "com.highcapable.pangutext",
    "module": "pangutext-android",
    "version": "1.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "pangutext-android-1.0.4.aar",
          "url": "pangutext-android-1.0.4.aar",
          "size": 68929,
          "sha512": "5177bd16b4ef27212b298283ab44bc8c2baceb5755149a3c18bdc07a2ad83a2dedbe7bfcc56b8c78368b5affbd89ec7d8d9d393cfb37530afeeb9af0f5429137",
          "sha256": "eadbcfaa59e5e490c61eaafb8e0ef881799811f4ac2564be91e45a1b0de06750",
          "sha1": "3cdf300637776f24d8f7f9d0d1e8fcd0fc3764bc",
          "md5": "b8b14fb38c30f37ce8edde47489bc0aa"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.highcapable.kavaref",
          "module": "kavaref-core",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.highcapable.kavaref",
          "module": "kavaref-extension",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.highcapable.betterandroid",
          "module": "ui-extension",
          "version": {
            "requires": "1.0.7"
          }
        },
        {
          "group": "com.highcapable.betterandroid",
          "module": "system-extension",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "pangutext-android-1.0.4.aar",
          "url": "pangutext-android-1.0.4.aar",
          "size": 68929,
          "sha512": "5177bd16b4ef27212b298283ab44bc8c2baceb5755149a3c18bdc07a2ad83a2dedbe7bfcc56b8c78368b5affbd89ec7d8d9d393cfb37530afeeb9af0f5429137",
          "sha256": "eadbcfaa59e5e490c61eaafb8e0ef881799811f4ac2564be91e45a1b0de06750",
          "sha1": "3cdf300637776f24d8f7f9d0d1e8fcd0fc3764bc",
          "md5": "b8b14fb38c30f37ce8edde47489bc0aa"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "pangutext-android-1.0.4-sources.jar",
          "url": "pangutext-android-1.0.4-sources.jar",
          "size": 23679,
          "sha512": "4827de1a077c408e4b9f7ccfcfc0ecd300bee178a069c642ddead361f1c26f26a68090e64759f17ae17dec6e9e6249fdcc3183c5fb1e018db53bffaacfd38145",
          "sha256": "c7c341b80d5ed5a2b85a2bd98fda264693dedc868f1684732c3756e9c564dcfb",
          "sha1": "ed1907e91682c476a6ee2b3da1c76ca9719491d3",
          "md5": "a6b531eebddf3ded37a7b8befa8ed1b4"
        }
      ]
    }
  ]
}
