{
  "formatVersion": "1.1",
  "component": {
    "group": "com.highcapable.hikage",
    "module": "hikage-widget-androidx",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "androidx.coordinatorlayout",
          "module": "coordinatorlayout",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.swiperefreshlayout",
          "module": "swiperefreshlayout",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.slidingpanelayout",
          "module": "slidingpanelayout",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.drawerlayout",
          "module": "drawerlayout",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.viewpager",
          "module": "viewpager",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.viewpager2",
          "module": "viewpager2",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "hikage-widget-androidx-1.0.0.aar",
          "url": "hikage-widget-androidx-1.0.0.aar",
          "size": 159291,
          "sha512": "e4d1ab2bc9819e0e3b56f8d375e877928cccde1a1481761c280b98741d033730f965ee8f77744b4292ed24eb28eb04113990c89050115a1d5a9e6ac4a0149f99",
          "sha256": "9da454d4daeaf08f7c369630ac1cbd2b9beb94c773bbbb879b5b897f86a1e225",
          "sha1": "afd2ba75c3d9b4a5b0b5103bd6da869dd6012ea3",
          "md5": "332efd6b1b38c6d4d1467a9857b958e7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.highcapable.hikage",
          "module": "hikage-core",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "androidx.coordinatorlayout",
          "module": "coordinatorlayout",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.swiperefreshlayout",
          "module": "swiperefreshlayout",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.slidingpanelayout",
          "module": "slidingpanelayout",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.drawerlayout",
          "module": "drawerlayout",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.viewpager",
          "module": "viewpager",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.viewpager2",
          "module": "viewpager2",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "hikage-widget-androidx-1.0.0.aar",
          "url": "hikage-widget-androidx-1.0.0.aar",
          "size": 159291,
          "sha512": "e4d1ab2bc9819e0e3b56f8d375e877928cccde1a1481761c280b98741d033730f965ee8f77744b4292ed24eb28eb04113990c89050115a1d5a9e6ac4a0149f99",
          "sha256": "9da454d4daeaf08f7c369630ac1cbd2b9beb94c773bbbb879b5b897f86a1e225",
          "sha1": "afd2ba75c3d9b4a5b0b5103bd6da869dd6012ea3",
          "md5": "332efd6b1b38c6d4d1467a9857b958e7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "hikage-widget-androidx-1.0.0-sources.jar",
          "url": "hikage-widget-androidx-1.0.0-sources.jar",
          "size": 13254,
          "sha512": "f628866d7e3b6b7fff98392f0873b576afb933dc9132a2c4999ee004f5f4916298c8952ba742bf86f1346075e8e0c577e7a297a07fd42b15009a8b18058b260d",
          "sha256": "1b7929089d28d7108287b5821870c8e6c879584d545a97cc0a4bab129bcdd8cc",
          "sha1": "1713e1842feb810751c1be37fea0e41c6a4b430d",
          "md5": "c2bdc8068fd3cab687a5a0b83b4b5679"
        }
      ]
    }
  ]
}
