{
  "formatVersion": "1.1",
  "component": {
    "url": "../../compose-extension/1.0.2/compose-extension-1.0.2.module",
    "group": "com.highcapable.betterandroid",
    "module": "compose-extension",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.5.11"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.5.11"
          }
        }
      ],
      "files": [
        {
          "name": "compose-extension.klib",
          "url": "compose-extension-iossimulatorarm64-1.0.2.klib",
          "size": 64217,
          "sha512": "79c711d1fc571356705f1890bfe3d1dcd07b948da9aa9507fb9ed899c3e31b186654b724d44a45d9825838dee1b5caf41c05db81330aaf68493ae85ce5882937",
          "sha256": "a11feeaca3edc2ae2189786df1f5f7d96776fd750ea42600d53e203b9749e13d",
          "sha1": "a88c13877ebfdf2303ea89491bb401a5fcfd168f",
          "md5": "e91b81558f1392abf7fc7843d004d8f7"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "compose-extension-iossimulatorarm64-1.0.2-sources.jar",
          "url": "compose-extension-iossimulatorarm64-1.0.2-sources.jar",
          "size": 25349,
          "sha512": "447212078defa053d1b4eab3e478fb48118a9f2c2c688d59d9e4e8438405aec54ccf5ccbd2b5ca970de561492fdd769800f7fb3c1cf69df41f735c00e74de4f8",
          "sha256": "36c0d5c9631ec69f7c06224e9a6db599949231cd0d6216bc49ec0365d1419571",
          "sha1": "121891441766c3246c5a0ce7d542865da147fcb9",
          "md5": "a920f04822156208f44eb28198ed63d3"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.5.11"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.5.11"
          }
        }
      ],
      "files": [
        {
          "name": "compose-extension-iossimulatorarm64-1.0.2-metadata.jar",
          "url": "compose-extension-iossimulatorarm64-1.0.2-metadata.jar",
          "size": 7892,
          "sha512": "4d2a975100e9864bd3d995c298430178eb3d7fac600806aa7082913e2dafa00b994c3f3aa93d9a9c8f5fa90dc2a94c09484ea0c8f218cd13e61bf574904a44e8",
          "sha256": "c787dac542fe4a698e31f72bfb87f7b990f600448d1611ba46728de2c0cefb53",
          "sha1": "4af7da0084d809b4a10c5c57fbaa7ed23b27d6d4",
          "md5": "2d473d550be864c4ec8c4a851c0d2757"
        }
      ]
    }
  ]
}
