{
  "formatVersion": "1.1",
  "component": {
    "url": "../../compose-multiplatform/0.1.0/compose-multiplatform-0.1.0.module",
    "group": "com.highcapable.betterandroid",
    "module": "compose-multiplatform",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        }
      ],
      "files": [
        {
          "name": "compose-multiplatform-release.aar",
          "url": "compose-multiplatform-android-0.1.0.aar",
          "size": 27771,
          "sha512": "a3b618a26ed42e324688da8d13023db737004b577bac1d5d4bbf0aacba4dc152e09063e596edca52db928635967d8f20a2db162c60df42f04677ff8ca2460746",
          "sha256": "5559bb7cd4d7aa597d47cab3e571d087aaa8e00782fcaf6f116ff07c2dcbd17d",
          "sha1": "ad126b0de8480a75b8891c7f5ab98c5feabe1686",
          "md5": "48626adea8585f358093849d7cc8989a"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.8.2"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "com.highcapable.betterandroid",
          "module": "ui-component",
          "version": {
            "requires": "1.0.4"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.5.11"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.5.11"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "com.highcapable.betterandroid",
          "module": "compose-extension",
          "version": {
            "requires": "1.0.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "compose-multiplatform-release.aar",
          "url": "compose-multiplatform-android-0.1.0.aar",
          "size": 27771,
          "sha512": "a3b618a26ed42e324688da8d13023db737004b577bac1d5d4bbf0aacba4dc152e09063e596edca52db928635967d8f20a2db162c60df42f04677ff8ca2460746",
          "sha256": "5559bb7cd4d7aa597d47cab3e571d087aaa8e00782fcaf6f116ff07c2dcbd17d",
          "sha1": "ad126b0de8480a75b8891c7f5ab98c5feabe1686",
          "md5": "48626adea8585f358093849d7cc8989a"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "compose-multiplatform-android-0.1.0-sources.jar",
          "url": "compose-multiplatform-android-0.1.0-sources.jar",
          "size": 18657,
          "sha512": "06666db8bb86a9d033ffa6211e570af2730c0586db5dc05105c2d9f0b63ea58632665ae69b1cd16751903019a26191054deb7c49961ebfebe017e391ec27565a",
          "sha256": "a9de889af8f1bfb6d89744fdea3e753624f353a0f91c324aff86a73a3289b377",
          "sha1": "7d96c0e41de583253899f5dd463937898a7b5bfa",
          "md5": "c59cc9cc94d7b385e709a397a8573ac5"
        }
      ]
    }
  ]
}
