{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.1.0-alpha01-dev0002/core-0.1.0-alpha01-dev0002.module",
    "group": "com.highcapable.flexiui",
    "module": "core",
    "version": "0.1.0-alpha01-dev0002",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.5.11"
          }
        },
        {
          "group": "com.highcapable.flexiui",
          "module": "resources",
          "version": {
            "requires": "0.1.0-alpha01"
          }
        },
        {
          "group": "com.highcapable.betterandroid",
          "module": "compose-extension",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.5.11"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-ripple",
          "version": {
            "requires": "1.5.11"
          }
        }
      ],
      "files": [
        {
          "name": "flexiui-core.klib",
          "url": "core-iosarm64-0.1.0-alpha01-dev0002.klib",
          "size": 595100,
          "sha512": "66949e4adf7c50384a8cfe6c3226ff7450c5c11823445f5caeb16adbf88903e4dd2aad736b97dcf841564657c7a1e6dc4791000bd0319707046124bc5664cef2",
          "sha256": "0ba17aacc8168171e65a08bcdcf0d596b599216518368bbc2a3ff2bd12ca39ba",
          "sha1": "f8b0627dc908e639e8b134c7c7c9ea5b994afc05",
          "md5": "c4dea80bdbf22e230daf0af3a6fd86ac"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "flexiui-core-iosarm64-0.1.0-alpha01-dev0002-sources.jar",
          "url": "core-iosarm64-0.1.0-alpha01-dev0002-sources.jar",
          "size": 88675,
          "sha512": "e6b626fd063a14773a7adf0652bade01e49d1cba9c13a6d8b63a77f091e2ffa7e2472de8d8100e94bc260001d607652ad476eebbb268147ed6bc123a1eb9aec5",
          "sha256": "565440741dedb588db68caf81c238041222c351487e6572a5f354583ee3631b8",
          "sha1": "4bd807c7abdc31e3ce9584c6271f3aecddf4f3ce",
          "md5": "cc2e3e3ba82c21fb178274c2e030086f"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.5.11"
          }
        },
        {
          "group": "com.highcapable.flexiui",
          "module": "resources",
          "version": {
            "requires": "0.1.0-alpha01"
          }
        },
        {
          "group": "com.highcapable.betterandroid",
          "module": "compose-extension",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.5.11"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-ripple",
          "version": {
            "requires": "1.5.11"
          }
        }
      ],
      "files": [
        {
          "name": "flexiui-core-iosarm64-0.1.0-alpha01-dev0002-metadata.jar",
          "url": "core-iosarm64-0.1.0-alpha01-dev0002-metadata.jar",
          "size": 6819,
          "sha512": "08d9a688879c3be7b14b4b4eb2449f0f4c4d8a108635f73fa8df24e68638441443fd707adea198a3110fb1fc1919641e17409d3ca45d9c0bfd5bb27f68c8277e",
          "sha256": "114175fcf3bd3248af5e7c6a01575c85a23cc6993f7fa8d1638b037d7c6f03f3",
          "sha1": "71e802d781b9f6eaf88a2f4851b5761e518440b1",
          "md5": "29b99dfc57ff687be0b874c0cbe7d595"
        }
      ]
    }
  ]
}
