{
  "formatVersion": "1.1",
  "component": {
    "group": "com.highcapable.betterandroid",
    "module": "ui-component",
    "version": "1.1.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "9.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "ui-component-1.1.5.aar",
          "url": "ui-component-1.1.5.aar",
          "size": 134127,
          "sha512": "dbd516e603ca2eea42c549478069e74e84680d9c4ecbe7a51b842125e711aed422fe5b87cfd92f11b0ad1e062796677b5ac99597e1cd53ccae9c0b504afbed79",
          "sha256": "0f8fb8529ea34fb53c65bc6d0314123d4a87573f4d83b0a7dedab4e8c4d98f38",
          "sha1": "fc3f76d4d288a6c902183cdca351f1d1e72afc18",
          "md5": "568da897dc587cc45074f8c2c2c0103c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.highcapable.betterandroid",
          "module": "ui-extension",
          "version": {
            "requires": "1.1.5"
          }
        },
        {
          "group": "com.highcapable.betterandroid",
          "module": "system-extension",
          "version": {
            "requires": "1.1.5"
          }
        },
        {
          "group": "com.highcapable.kavaref",
          "module": "kavaref-bom",
          "version": {
            "requires": "1.1.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.highcapable.kavaref",
          "module": "kavaref-core"
        },
        {
          "group": "com.highcapable.kavaref",
          "module": "kavaref-android"
        },
        {
          "group": "com.highcapable.kavaref",
          "module": "kavaref-extension"
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "9.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "ui-component-1.1.5.aar",
          "url": "ui-component-1.1.5.aar",
          "size": 134127,
          "sha512": "dbd516e603ca2eea42c549478069e74e84680d9c4ecbe7a51b842125e711aed422fe5b87cfd92f11b0ad1e062796677b5ac99597e1cd53ccae9c0b504afbed79",
          "sha256": "0f8fb8529ea34fb53c65bc6d0314123d4a87573f4d83b0a7dedab4e8c4d98f38",
          "sha1": "fc3f76d4d288a6c902183cdca351f1d1e72afc18",
          "md5": "568da897dc587cc45074f8c2c2c0103c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-component-1.1.5-sources.jar",
          "url": "ui-component-1.1.5-sources.jar",
          "size": 45768,
          "sha512": "2c25c5ddb406e4b673026627232dad40e0c4c9801f94ffc093717e3ef4dd1454c4d9aecd8c5d42969a7378d11cd9ba65091898a08b67650a7c6e9144b6a115e6",
          "sha256": "2e9461e7b41ef466a5da02178ec3546ca75b90f34c39e43a47b8ab5eec0c64a0",
          "sha1": "6315d11288cacb393407a914ab2e98487b10fb6b",
          "md5": "5c32614b3acdcadd96a9ab6e417c7b93"
        }
      ]
    }
  ]
}
