{
  "formatVersion": "1.1",
  "component": {
    "group": "com.highcapable.hikage",
    "module": "hikage-core",
    "version": "1.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.highcapable.betterandroid",
          "module": "ui-extension",
          "version": {
            "requires": "1.0.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "hikage-core-1.0.4.aar",
          "url": "hikage-core-1.0.4.aar",
          "size": 285959,
          "sha512": "a41e7759c6787decbf82b70335ad3586a7db9d1c6e85e271ab6b75c00dbb84a9656dd5f976c38009b9ce58df0d06b32d9e15cbde4d40d495ced9ae20f0bd471b",
          "sha256": "b135e143f074f585f3f220fe87763b359c3d36000a856cfd4daa459fcdcc88e4",
          "sha1": "3dd77de3b2b1150f4f3fba34e98b585f48626758",
          "md5": "cd5576bee3924f7c8ac54f1a9ffa5976"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.lsposed.hiddenapibypass",
          "module": "hiddenapibypass",
          "version": {
            "requires": "6.1"
          }
        },
        {
          "group": "com.highcapable.kavaref",
          "module": "kavaref-core",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "com.highcapable.kavaref",
          "module": "kavaref-extension",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "com.highcapable.betterandroid",
          "module": "system-extension",
          "version": {
            "requires": "1.0.4"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.highcapable.betterandroid",
          "module": "ui-extension",
          "version": {
            "requires": "1.0.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "hikage-core-1.0.4.aar",
          "url": "hikage-core-1.0.4.aar",
          "size": 285959,
          "sha512": "a41e7759c6787decbf82b70335ad3586a7db9d1c6e85e271ab6b75c00dbb84a9656dd5f976c38009b9ce58df0d06b32d9e15cbde4d40d495ced9ae20f0bd471b",
          "sha256": "b135e143f074f585f3f220fe87763b359c3d36000a856cfd4daa459fcdcc88e4",
          "sha1": "3dd77de3b2b1150f4f3fba34e98b585f48626758",
          "md5": "cd5576bee3924f7c8ac54f1a9ffa5976"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "hikage-core-1.0.4-sources.jar",
          "url": "hikage-core-1.0.4-sources.jar",
          "size": 103465,
          "sha512": "4ff8c0d76492e9756d4a3423d6c22c8cb6c32ae24c049adf3b1987b00ca429729ec771e340bd7ed8143852c0476364db28e72dcddf9e7eb0e568791d047606ad",
          "sha256": "4ad1e54b7e9f5df8117315e5cef068ac482aad8e7158796547622cac15df086f",
          "sha1": "b294881545c0809ae8a50700d92ebb26ffbfb392",
          "md5": "55b63efac8269c0167842bdc515c95f3"
        }
      ]
    }
  ]
}
