{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.1.0-alpha01-dev0005/core-0.1.0-alpha01-dev0005.module",
    "group": "com.highcapable.flexiui",
    "module": "core",
    "version": "0.1.0-alpha01-dev0005",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.5.11"
          }
        },
        {
          "group": "com.highcapable.flexiui",
          "module": "resources",
          "version": {
            "requires": "0.1.0-alpha01"
          }
        },
        {
          "group": "com.highcapable.betterandroid",
          "module": "compose-extension",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.5.11"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-ripple",
          "version": {
            "requires": "1.5.11"
          }
        }
      ],
      "files": [
        {
          "name": "flexiui-core.klib",
          "url": "core-iosarm64-0.1.0-alpha01-dev0005.klib",
          "size": 599431,
          "sha512": "c597908fc2dba2e297e64ac800c87cca95cca9e9ae3cb35e390338aee30714e5be14b09a250672d071526fe25e3bb9dd0a8307c06af4c341301ca85f9a016825",
          "sha256": "1b08bf992a394e610c7eca7b19da3ed409e3fbf88cfff14725d4ef17583f9478",
          "sha1": "20e101dd21afd7f9126e94287f3dd2da43cd5122",
          "md5": "73cbcf9e3ae0beb30317a9820a11e4d0"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "flexiui-core-iosarm64-0.1.0-alpha01-dev0005-sources.jar",
          "url": "core-iosarm64-0.1.0-alpha01-dev0005-sources.jar",
          "size": 89512,
          "sha512": "da25bd5082231f5adeaf4ea721f37ebf4a1dd32d205be1ecb55c44d37fde6939d55e880cf8a1571469a56e0a08b24b7d5b52937632bba2407e25dcec8b08e3e6",
          "sha256": "9f330e8b27086f4d8ff80c27ae2009159c51f73070886f327c29a54c90ea33b4",
          "sha1": "740ece8dd7f4a60811e934457cf7aaa31814669a",
          "md5": "15e78cbbf2148fc96a26f3368b31e46d"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.5.11"
          }
        },
        {
          "group": "com.highcapable.flexiui",
          "module": "resources",
          "version": {
            "requires": "0.1.0-alpha01"
          }
        },
        {
          "group": "com.highcapable.betterandroid",
          "module": "compose-extension",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.5.11"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-ripple",
          "version": {
            "requires": "1.5.11"
          }
        }
      ],
      "files": [
        {
          "name": "flexiui-core-iosarm64-0.1.0-alpha01-dev0005-metadata.jar",
          "url": "core-iosarm64-0.1.0-alpha01-dev0005-metadata.jar",
          "size": 6819,
          "sha512": "74ac099253251b7dc189dc041654c28eddefa6c4a6047fdf2ff79f5484f962a41574610f89f92fbd4ac830fe896f2fc60774ebddfb7ae0cae6c405b413cc0cd1",
          "sha256": "30bc6e3b7e20303b40b3f63cf3fb581818ae059b760fb494aff48d88845cd10b",
          "sha1": "bed92f4256ab5aa00e957ff56e4e5581cfafab1b",
          "md5": "f412bdb4c4867dae69f8c365e254b446"
        }
      ]
    }
  ]
}
