{
  "formatVersion": "1.1",
  "component": {
    "group": "com.highcapable.betterandroid",
    "module": "ui-component",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.1.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "ui-component-1.0.0.aar",
          "url": "ui-component-1.0.0.aar",
          "size": 190035,
          "sha512": "12a869bf27f168a628609bbe8ac2e0e7c6c2d8eb33dbd08ad3ea19d7efe5c3fafc74f9367c2887076fdf87cf5e0960b36c98650d142adb4cfd36c5eb984a9492",
          "sha256": "ada0663e5346c291763ce3240bd3018681f15c27ee0d7b79d4d62ea21e3061e9",
          "sha1": "5994899cea6aaaaa619f214a40a932e3cbc214de",
          "md5": "648aae9db1a0e75c5ed293c02dcdb629"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.highcapable.betterandroid",
          "module": "ui-extension",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.highcapable.betterandroid",
          "module": "system-extension",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.highcapable.yukireflection",
          "module": "api",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.1.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "ui-component-1.0.0.aar",
          "url": "ui-component-1.0.0.aar",
          "size": 190035,
          "sha512": "12a869bf27f168a628609bbe8ac2e0e7c6c2d8eb33dbd08ad3ea19d7efe5c3fafc74f9367c2887076fdf87cf5e0960b36c98650d142adb4cfd36c5eb984a9492",
          "sha256": "ada0663e5346c291763ce3240bd3018681f15c27ee0d7b79d4d62ea21e3061e9",
          "sha1": "5994899cea6aaaaa619f214a40a932e3cbc214de",
          "md5": "648aae9db1a0e75c5ed293c02dcdb629"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-component-1.0.0-sources.jar",
          "url": "ui-component-1.0.0-sources.jar",
          "size": 74293,
          "sha512": "3b01517adcac13cfb7a225ac200ee463c457b3d8b9ca4c761e417892740f9949131dcd442aa16d73cad0c6987ec6b7e1a5986d2d05e478fae1bdb64cb8131656",
          "sha256": "d19aae733ca2b42deabf14d1c9587d4c8ffd20390162009a8cd491fd199b7d02",
          "sha1": "bf97d1e7a7bed96b5f190c826a753d0b3cbf4bc6",
          "md5": "2f99554ddb5fab8917af9f0ea5801699"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-component-1.0.0-javadoc.jar",
          "url": "ui-component-1.0.0-javadoc.jar",
          "size": 668749,
          "sha512": "4da41d8cef6310368a06365a702548c028e02b43a8c09ca64ad16b35ca2166ac0232b31b050f8ab2d9e6deb1ca918dd9493bf3422e204d757599e9d4601336fa",
          "sha256": "e4d3fa6cf818fad0da2041c63a89515bab218d69af786a7c9d45d24f5313f5ad",
          "sha1": "cb3cd3527420b919a890c11d0fd8550b9da23323",
          "md5": "a2a6c0e6d4b8aeef8877dab7c7ea8611"
        }
      ]
    }
  ]
}
