{
  "formatVersion": "1.1",
  "component": {
    "url": "../../compose-extension/1.0.2/compose-extension-1.0.2.module",
    "group": "com.highcapable.betterandroid",
    "module": "compose-extension",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.5.11"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.5.11"
          }
        }
      ],
      "files": [
        {
          "name": "compose-extension.klib",
          "url": "compose-extension-iosx64-1.0.2.klib",
          "size": 64115,
          "sha512": "41726a35560ca4006d3daeb2d61a80b3770b1723fb794d4d69808b86796e4a6f16283f53088c49438923413a862caa5843cc69780efc5dbe367707dcbc1c3874",
          "sha256": "d3058aa06e03032f2839693808e4603cd554e0b51d666f7a572cdbcb173bc354",
          "sha1": "9afdfec390537a73fd2282c09655634a16f68724",
          "md5": "31f59b50265e00175ff5b16125717925"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "compose-extension-iosx64-1.0.2-sources.jar",
          "url": "compose-extension-iosx64-1.0.2-sources.jar",
          "size": 25173,
          "sha512": "35cb828cfcd1e72ce11296f9ef39721689f02aba5fb1867b2e5eb29feb6a8c131ee2edad167be511c632836b3ee2d08b646ea4999daeff43fd22b70fd49db3c4",
          "sha256": "23c0dada07c8c636fea78e1143dda6a10f5308a8bb83195ed32730748d9f52dc",
          "sha1": "26558f3a9d33ce6b79f2ce5471d42fda6c58387a",
          "md5": "52a103ed51ffd0224a26da5d1986bcdc"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.5.11"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.5.11"
          }
        }
      ],
      "files": [
        {
          "name": "compose-extension-iosx64-1.0.2-metadata.jar",
          "url": "compose-extension-iosx64-1.0.2-metadata.jar",
          "size": 7892,
          "sha512": "ca4c6be4d0c44f25bd787205077c8a10c714b3d2c08c3c6b2adde1bc1e83ce408f2e7862f9c185f5ce9894beab864b5c5ab7684e41a4bb2625bf640a4705532b",
          "sha256": "be5ea7dee11ec156c45b6c3e8a9cb17b3f40f9b4a7912eca43f24430dd93242d",
          "sha1": "12f4f44a3e2370615521e4b86f9e8e3500e7349a",
          "md5": "f9349ce008a3cbd2df5fc5a16b96a224"
        }
      ]
    }
  ]
}
