{
  "formatVersion": "1.1",
  "component": {
    "group": "com.highcapable.flexiui",
    "module": "core",
    "version": "0.1.0-alpha01-dev0004",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.5.11"
          }
        },
        {
          "group": "com.highcapable.flexiui",
          "module": "resources",
          "version": {
            "requires": "0.1.0-alpha01"
          }
        },
        {
          "group": "com.highcapable.betterandroid",
          "module": "compose-extension",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.5.11"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-ripple",
          "version": {
            "requires": "1.5.11"
          }
        }
      ],
      "files": [
        {
          "name": "flexiui-core-metadata-0.1.0-alpha01-dev0004.jar",
          "url": "core-0.1.0-alpha01-dev0004.jar",
          "size": 33535,
          "sha512": "f6f493e0e676534503cfc0e1a6af2b714b2ffccf3466f007b2b7b585ed2bf95aed75029799efaad096467674b9d1b170faed0d776268ad97e82d84abd254c5ec",
          "sha256": "4e93666d19d8dd1d2108efa4ca8b389884fd00852fcb8f5ae5ad3256546db49b",
          "sha1": "5b96a579ca1059ced5b7cccc9fba85bed6374185",
          "md5": "0a78fd224dff2c1f1b2f19a7dd77ad5e"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "flexiui-core-kotlin-0.1.0-alpha01-dev0004-sources.jar",
          "url": "core-0.1.0-alpha01-dev0004-sources.jar",
          "size": 87619,
          "sha512": "050e36edf31f54f991dd7afed4f2c698c4f7000d57f2712b88daff6f50c6bb792416957233f9fd646d51bc11e3b82d19794ef2cd95474bb414261261cc56da38",
          "sha256": "7fa5bf191be614e5ffc351f00941e45259d7710eb9e0940cbbdb39c2b9db04a4",
          "sha1": "542588b12cc61dc523a50a93a223fea331fc60cc",
          "md5": "f12de91e616c05b8c56946b96915299c"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../core-android/0.1.0-alpha01-dev0004/core-android-0.1.0-alpha01-dev0004.module",
        "group": "com.highcapable.flexiui",
        "module": "core-android",
        "version": "0.1.0-alpha01-dev0004"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../core-android/0.1.0-alpha01-dev0004/core-android-0.1.0-alpha01-dev0004.module",
        "group": "com.highcapable.flexiui",
        "module": "core-android",
        "version": "0.1.0-alpha01-dev0004"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../core-android/0.1.0-alpha01-dev0004/core-android-0.1.0-alpha01-dev0004.module",
        "group": "com.highcapable.flexiui",
        "module": "core-android",
        "version": "0.1.0-alpha01-dev0004"
      }
    },
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../core-desktop/0.1.0-alpha01-dev0004/core-desktop-0.1.0-alpha01-dev0004.module",
        "group": "com.highcapable.flexiui",
        "module": "core-desktop",
        "version": "0.1.0-alpha01-dev0004"
      }
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../core-desktop/0.1.0-alpha01-dev0004/core-desktop-0.1.0-alpha01-dev0004.module",
        "group": "com.highcapable.flexiui",
        "module": "core-desktop",
        "version": "0.1.0-alpha01-dev0004"
      }
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../core-desktop/0.1.0-alpha01-dev0004/core-desktop-0.1.0-alpha01-dev0004.module",
        "group": "com.highcapable.flexiui",
        "module": "core-desktop",
        "version": "0.1.0-alpha01-dev0004"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-iosarm64/0.1.0-alpha01-dev0004/core-iosarm64-0.1.0-alpha01-dev0004.module",
        "group": "com.highcapable.flexiui",
        "module": "core-iosarm64",
        "version": "0.1.0-alpha01-dev0004"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-iosarm64/0.1.0-alpha01-dev0004/core-iosarm64-0.1.0-alpha01-dev0004.module",
        "group": "com.highcapable.flexiui",
        "module": "core-iosarm64",
        "version": "0.1.0-alpha01-dev0004"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-iosarm64/0.1.0-alpha01-dev0004/core-iosarm64-0.1.0-alpha01-dev0004.module",
        "group": "com.highcapable.flexiui",
        "module": "core-iosarm64",
        "version": "0.1.0-alpha01-dev0004"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-iossimulatorarm64/0.1.0-alpha01-dev0004/core-iossimulatorarm64-0.1.0-alpha01-dev0004.module",
        "group": "com.highcapable.flexiui",
        "module": "core-iossimulatorarm64",
        "version": "0.1.0-alpha01-dev0004"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-iossimulatorarm64/0.1.0-alpha01-dev0004/core-iossimulatorarm64-0.1.0-alpha01-dev0004.module",
        "group": "com.highcapable.flexiui",
        "module": "core-iossimulatorarm64",
        "version": "0.1.0-alpha01-dev0004"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-iossimulatorarm64/0.1.0-alpha01-dev0004/core-iossimulatorarm64-0.1.0-alpha01-dev0004.module",
        "group": "com.highcapable.flexiui",
        "module": "core-iossimulatorarm64",
        "version": "0.1.0-alpha01-dev0004"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-iosx64/0.1.0-alpha01-dev0004/core-iosx64-0.1.0-alpha01-dev0004.module",
        "group": "com.highcapable.flexiui",
        "module": "core-iosx64",
        "version": "0.1.0-alpha01-dev0004"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-iosx64/0.1.0-alpha01-dev0004/core-iosx64-0.1.0-alpha01-dev0004.module",
        "group": "com.highcapable.flexiui",
        "module": "core-iosx64",
        "version": "0.1.0-alpha01-dev0004"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-iosx64/0.1.0-alpha01-dev0004/core-iosx64-0.1.0-alpha01-dev0004.module",
        "group": "com.highcapable.flexiui",
        "module": "core-iosx64",
        "version": "0.1.0-alpha01-dev0004"
      }
    }
  ]
}
