{
  "formatVersion": "1.1",
  "component": {
    "group": "com.highcapable.betterandroid",
    "module": "ui-component",
    "version": "1.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.5.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "ui-component-1.0.6.aar",
          "url": "ui-component-1.0.6.aar",
          "size": 231099,
          "sha512": "aefb54d5194b65b2bdae74b3510e7cf36b554b236e94b16e53b13690360bd6e0f5172bd2a76ec0ba9c002a2ba9f1cf314cd745f0f3fd2a770802b1edf452baa4",
          "sha256": "5b90f77d7fc56c03e46207aad522ebc3f345e95f78f367f0b627f5b5ddf33b39",
          "sha1": "b04a2b223ffba0f8547adaeb6a5fdf515542f9a6",
          "md5": "c55c915ee6114627335be47869f52f73"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.highcapable.betterandroid",
          "module": "ui-extension",
          "version": {
            "requires": "1.0.5"
          }
        },
        {
          "group": "com.highcapable.betterandroid",
          "module": "system-extension",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "com.highcapable.yukireflection",
          "module": "api",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.5.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "ui-component-1.0.6.aar",
          "url": "ui-component-1.0.6.aar",
          "size": 231099,
          "sha512": "aefb54d5194b65b2bdae74b3510e7cf36b554b236e94b16e53b13690360bd6e0f5172bd2a76ec0ba9c002a2ba9f1cf314cd745f0f3fd2a770802b1edf452baa4",
          "sha256": "5b90f77d7fc56c03e46207aad522ebc3f345e95f78f367f0b627f5b5ddf33b39",
          "sha1": "b04a2b223ffba0f8547adaeb6a5fdf515542f9a6",
          "md5": "c55c915ee6114627335be47869f52f73"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-component-1.0.6-sources.jar",
          "url": "ui-component-1.0.6-sources.jar",
          "size": 98132,
          "sha512": "8e24f80084e647fe7d15265c7ca2ef64dc7d7a01118e5fb10bb11eb038e2f1e8bc763a09cea4d1d08404f3eee9388346d824b32fbedb7a8d833ff21878668802",
          "sha256": "0f3ae116e7b13e87341acdf242baa8a3e048c9031b953b2aab6706561625a565",
          "sha1": "256ba44f0b37c3a2ef60383420912781f59deb1d",
          "md5": "26ad7c3afdbe2a22643dd1d9d418af09"
        }
      ]
    }
  ]
}
